<?php
// $Id$

/**
 * @file
 * Install and uninstall schema and functions for the xmlsitemap_custom module.
 */

/**
 * Implementation of hook_uninstall().
 */
function xmlsitemap_custom_uninstall() {
  db_query("DELETE FROM {xmlsitemap} WHERE type = 'custom'");

  // Remove variables.
  drupal_load('module', 'xmlsitemap_custom');
  //$variables = array_keys(xmlsitemap_custom_variables());
  //foreach ($variables as $variable) {
  //  variable_del($variable);
  //}
}
