#!/bin/sh

git checkout patches
git merge drupal
git checkout devel
git merge patches
git checkout site-config
git merge devel
git checkout mangle
git merge site-config
diff --strip-trailing-cr -NuBr drupal-6.x /home/data/backups/1and1/backup-1and1-2011.04.07a/drupal-nocvsid > ../git-backup.diff
git checkout drupal
