<?php
// $Id$

/**
 * Implementation of hook_form_FORM_ID_alter().
 *
 * Set the regeneration needed flag if multilingual settings are changed.
 */
function xmlsitemap_i18n_form_i18n_admin_settings_alter(&$form, $form_state) {
  array_unshift($form['#submit'], 'xmlsitemap_form_submit_flag_regenerate');
}

/**
 * Implementation of hook_xmlsitemap_query_alter().
 *
 * @see i18n_db_rewrite_where()
 */
function xmlsitemap_i18n_xmlsitemap_query_alter(array &$query, array &$args, $language) {
  // Get languages to simplify query building.
  $mode = variable_get('i18n_selection_mode', 'simple');
  //$current = i18n_get_lang();
  $current = $language->language;
  $default = i18n_default_language();

  if ($mode == 'mixed' && $current == $default) {
    // If mode is mixed but current = default, is the same as 'simple'.
    $mode = 'simple';
  }

  switch ($mode) {
    case 'simple':
      // Current language and language neutral.
      $query['WHERE'] .= " AND x.language IN ('%s', '')";
      $args[] = $current;
      break;
    case 'mixed':
      // Mixed current language (if available) or default language (if not) and language neutral.
      $query['WHERE'] .= " AND x.language IN ('%s', '%s', '')";
      $args[] = $current;
      $args[] = $default;
      break;
    case 'default':
      // Only default language and language neutral.
      $query['WHERE'] .= " AND x.language IN ('%s', '')";
      $args[] = $default;
      break;
    case 'strict':
      // Only current language (for nodes), simple for all other types.
      $query['WHERE'] .= " AND ((x.type = 'node' AND x.language = '%s') OR (x.type <> 'node' AND x.language IN ('%s', '')))";
      $args[] = $current;
      $args[] = $current;
      break;
    case 'off':
      // All content. No language conditions apply.
      break;
  }
}
