<?php

function amazon_media_form_alter(&$form, $form_state) {
  if ($form['#id'] == 'amazon-storage-settings-form') {
    $form['details']['amazon_media_data'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Store media and software details'),
      '#options' => array(
         'ABIS_BOOK' => t('Book publication details'),
         'ABIS_DVD' => t('DVD release details'),
         'ABIS_MUSIC' => t('Music recording details'),
         'ABIS_SOFTWARE' => t('Software platform information'),
         'ABIS_VIDEO_GAMES' => t('Video game platform information'),
      ),
      '#default_value' => variable_get('amazon_media_data', array('ABIS_BOOK', 'ABIS_DVD', 'ABIS_MUSIC')),
    );
  }
}

function amazon_media_amazon_item_load(&$item) {
  if (in_array($item['producttypename'], variable_get('amazon_media_data', array('ABIS_BOOK', 'ABIS_DVD', 'ABIS_MUSIC')))) {
    switch ($item['producttypename']) {
      case 'ABIS_BOOK':
        $additions = db_fetch_array(db_query("SELECT * FROM {amazon_book} WHERE asin = '%s'", $item['asin']));
        break;
      case 'ABIS_DVD':
        $additions = db_fetch_array(db_query("SELECT * FROM {amazon_dvd} WHERE asin = '%s'", $item['asin']));
        break;
      case 'ABIS_MUSIC':
        $additions = db_fetch_array(db_query("SELECT * FROM {amazon_music} WHERE asin = '%s'", $item['asin']));
        break;
      case 'ABIS_VIDEO_GAMES':
      case 'ABIS_SOFTWARE':
        $additions = db_fetch_array(db_query("SELECT * FROM {amazon_software} WHERE asin = '%s'", $item['asin']));
        break;
    }
    if (isset($additions)) {
      $item += $additions;
    }
  }
}

function amazon_media_amazon_item_insert($item) {
  if (in_array($item['producttypename'], variable_get('amazon_media_data', array('ABIS_BOOK', 'ABIS_DVD', 'ABIS_MUSIC')))) {
    switch ($item['producttypename']) {
      case 'ABIS_BOOK':
        drupal_write_record('amazon_book', $item);
        break;
      case 'ABIS_DVD':
        drupal_write_record('amazon_dvd', $item);
        break;
      case 'ABIS_MUSIC':
        drupal_write_record('amazon_music', $item);
        break;
      case 'ABIS_VIDEO_GAMES':
      case 'ABIS_SOFTWARE':
        drupal_write_record('amazon_software', $item);
        break;
    }
  }
}

function amazon_media_amazon_item_delete($asin) {
  // This is pretty inefficient; we're going to thrash these tables
  // every time a product gets deleted or updated. We'll solve it later.
  db_query("DELETE FROM {amazon_book} WHERE asin = '%s'", $asin);
  db_query("DELETE FROM {amazon_dvd} WHERE asin = '%s'", $asin);
  db_query("DELETE FROM {amazon_music} WHERE asin = '%s'", $asin);
  db_query("DELETE FROM {amazon_software} WHERE asin = '%s'", $asin);
}
