<?php
// $Id$

function amazon_media_install() {
  drupal_install_schema('amazon_media');
  $existing = amazon_get_cacheable_chunk_list();
  $existing += array('ABIS_BOOK', 'ABIS_DVD', 'ABIS_MUSIC');
  variable_set('amazon_extra_data', $existing);
}

function amazon_media_uninstall() {
  db_query("DROP TABLE {amazon_book}");
  db_query("DROP TABLE {amazon_dvd}");
  db_query("DROP TABLE {amazon_music}");
  db_query("DROP TABLE {amazon_software}");
}
