<?php

/**
*  Implementation of hook_form_alter()
*/
function drupalforfirebug_preprocess_form_alter($formid, &$form) {
  $_SESSION['drupalforfirebug_forms']['original'][$formid] = $form;
}

function drupalforfirebug_preprocess_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  $nid = ($node->nid) ? $node->nid : '*NEW*';
  $_SESSION['drupalforfirebug_nodes']['original'][$node->type][$nid] = $node;
}
