<?php

/** 
 * FCKEditor Module
 * 
 * This module allows Drupal to replace textarea fields with FCKEditor. This HTML 
 * text editor brings to the web many of the powerful functionalities of known 
 * desktop editors like Word. It's really  lightweight and doesn't require any 
 * kind of installation on the client computer.
 * 
 * 
 * FCKeditor - The text editor for internet
 * Copyright (C) 2003-2004 Frederico Caldeira Knabben
 * 
 * Licensed under the terms of the GNU Lesser General Public License:
 * 		http://www.opensource.org/licenses/lgpl-license.php
 * 
 * For further information visit:
 * 		http://www.fckeditor.net/
 *
 *
 * @version 1.0
 * @author  LatPro Inc (George)
 */


/**
 * Implementation of hook_help
 */
function fckeditor_help($section = '') {
	if ($section == 'admin/modules#description') {
		return $output = t("Allows Drupal to replace textarea fields with FCKEditor");
	}
	return $output;
}


/**
 * Implementation of hook_perm
 */
function fckeditor_perm() {
	return array('use fckeditor');
}


/**
 * Implementation of textarea
 */
function fckeditor_textarea($op, $name) {
	$output = '';
	$access = user_access('use fckeditor');

	if ( fckeditor_is_compatible_client() && $access ) {
		if ( $op == 'pre' ) {
			$output = '';
		}
		if ( $op == 'post' ) {
			$output = "<script>document.getElementById('edit-$name').style.display = 'none';</script>";
			$output .= fckeditor_create_editor($name);
		}
	}
	return $output;
}


/**
 * Implementation of hook_setting().
 */
function fckeditor_settings() {
	$output = form_textfield(
		t("Base Path"), 
		"fckeditor_base_path", 
		variable_get("fckeditor_base_path", '/modules/fckeditor/lib/'), 
		60, 255, t('The directory wich contains FCKEditor scripts'));
		
	$output .= form_select(
		t('Toolbar'), 
		'fckeditor_toolbar', 
		variable_get('fckeditor_toolbar', 'Default'), 
		array('Default' => 'Default', 'Basic' => 'Basic'), 
		t('The toolbar set.'));

	$output .= form_select(
		t('Skin'), 
		'fckeditor_skin', 
		variable_get('fckeditor_skin', 'default'), 
		array('default' => 'Default', 'silver' => 'Silver', 'office2003' => 'Office 2003'), 
		t('The toolbar set.'));

	$output .= form_select(
		t('Toolbar start expanded'), 
		'fckeditor_toolbar_start_expanded', 
		variable_get('fckeditor_toolbar_start_expanded', 'true'), 
		array('true' => 'Yes', 'false' => 'No'), 
		t('The toolbar start expanded or colapced.'));

	$output .= form_textfield(
		t("Height"), 
		"fckeditor_height", 
		variable_get("fckeditor_height", 500), 
		10, 10, t("height (pixels/percent)"));
		
	$output .= form_textfield(
		t("Width"), "fckeditor_width", 
		variable_get("fckeditor_width", '100%'), 
		10, 10, t("width (pixels/percent)"));
		
	return $output;
}  



/**
 * This function create the HTML objects required for the FCKEditor
 */
function fckeditor_create_editor($name) {
	$html = '';
	$base_path = variable_get("fckeditor_base_path", '/modules/fckeditor/lib/');
	
	$link = "$base_path/editor/fckeditor.html?InstanceName=edit-$name";
	$link .= '&Toolbar=' . variable_get("fckeditor_toolbar", 'Default');
	
	$height = variable_get("fckeditor_height", '500');
	$width = variable_get("fckeditor_width", '100%');
	
	
	// Render the configurations hidden field.
	$html .= '<input type="hidden" id="edit-';
	$html .= $name;
	$html .= '___Config" value="';
	$html .= fckeditor_config_string();
	$html .= '">';

	// Render the editor IFRAME.
	$html .= '<iframe id="edit-';
	$html .= $name;
	$html .= '___Frame" src="';
	$html .= $link;
	$html .= "\" width=\"$width\" height=\"$height\" frameborder=\"no\" scrolling=\"no\"></iframe>" ;

	return $html;	
}


/**
 * Test if client support the FCKEditor
 */
function fckeditor_is_compatible_client() {
	$sAgent = $_SERVER['HTTP_USER_AGENT'] ;
	
	if ( strpos($sAgent, 'MSIE') !== false && strpos($sAgent, 'mac') === false && strpos($sAgent, 'Opera') === false ) {
		$iVersion = (int)substr($sAgent, strpos($sAgent, 'MSIE') + 5, 3);
		return ($iVersion >= 5.5);
	}
	else if ( strpos($sAgent, 'Gecko') !== false ) {
		$iVersion = (int)substr($sAgent, strpos($sAgent, 'Gecko/') + 6, 8) ;
		return ($iVersion >= 20030210) ;
	}
	else
		return false;
}


/**
 * Return the configuration string
 */
function fckeditor_config_string() {
	$base_path = variable_get("fckeditor_base_path", 'modules/fckeditor/lib');
	$skin = variable_get("fckeditor_skin", 'default');
	$start = variable_get('fckeditor_toolbar_start_expanded', 'true');
	
	$output = '&DefaultLanguage=en&AutoDetectLanguage=true';
	$output .= '&SkinPath=' . $base_path . "editor/skins/$skin/";
	$output .= '&ToolbarStartExpanded=' . $start;
	
	return $output;
}
?>