<?php
// $id: feedback.module,v 1.2 2002/05/26 21:03:00 barry Exp $

function feedback_system($field) {
  $system["description"] = t("the feedback module allows user to email the site admin via a web based form");
  return $system[$field];
}

function feedback_conf_options() {
  $output .= form_textfield(t("Administrative Contact"), "feedback_module_email", variable_get("feedback_module_email", variable_get("site_email", ini_get("sendmail_from"))) , 55, 128, t("Enter an email address here is you wish the feedback module to send to an alternative address to the site email variable"));
  $output .= form_textarea(t("Feedback Message"), "feedback_module_message", variable_get("feedback_module_message", "Enter your message below:"), 60, 20, t("Enter the message that will appear above the feedback form"));
  return $output;
}

function feedback_perm() {
  return array("send feedback");
}

function feedback_link($type, $node = 0) {
  if (($type == "page") && user_access("send feedback")) {
    $links[] = lm(t("feedback"), array("mod" => "feedback"), t("Send the site administrator(s) feedback"));
  }
  
  return $links ? $links : array();
}

function feedback_page() {
  global $page, $theme;

  if(user_access("send feedback")) {

    $page = $page ? $page : "default";
    $f = "_feedback_page_" . $page;

    if (function_exists($f)) {
      $f();
    }

  } else {

    $theme->header();
    $theme->box(t("Access denied"), message_access());
    $theme->footer();
  
  }

}

function _feedback_page_default() {
  global $theme;

  $title  .= t("Feedback");

  $message .= "<br /><p>". variable_get("feedback_module_message", "Enter your message below:") ."</p>";

  $form .= form_textfield(t("Subject"), "subject", $edit[subject], 60, 64);
  $form .= form_textarea(t("Body"), "message", $edit[message], 60, 20);
  $form .= form_submit(t("send"));

  $theme->header();
  $theme->box($title, $message . form($form, "post", "module.php?mod=feedback&page=send"));
  $theme->footer();

}

function _feedback_page_send() {
  global $theme, $edit, $user;
  $to = variable_get("feedback_module_email", "site_email");
  $from = $user->mail ? $user->mail : variable_get("site_email", "");
  $who = $user->name ? $user->name : "anonymous";
  $subject = $edit[subject];
  $body = "-- $who sent you the following message using the feedback page --\n" . $edit[message];
  $body = wordwrap(strip_tags($body),72);
  $trans = get_html_translation_table(HTML_ENTITIES);
  $trans = array_flip($trans);
  $body = strtr($body, $trans);
  
  user_mail($to, $subject, $body, "From: $from\nReply-to: $from\nX-Mailer: Drupal\nReturn-path: $from\nErrors-to: $from");

  $title .= t("Feedback Confirmation");
  $message .= "<br /><p>". t("Your message has been sent to the Administrator's Email account.") ."</p>";

  $theme->header();
  $theme->box($title, $message);
  $theme->footer();
}
