<?php

/**
 * @file
 * field upload element demonstration module.
 */

include_once('field_file.inc');
/**
 * @defgroup core_hooks
 * @{
 */

/**
 * Implementation of hook_menu().
 */
function field_upload_menu() {
  $items = array();
  $items['field/upload'] = array(
    'page callback' =>  'drupal_get_form',
    'page arguments' => array('field_upload_form'),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );  
  $items['field/upload/js'] = array(
    'page callback' => 'imagefield_js',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function field_upload_theme() {
  return array(
    'field_upload' => array(
      'arguments' => array('element' => null),
    ),
    'field_file' => array(
      'arguments' => array('element' => null),
    ),  
  );
}

/**
 * Implementation of hook_elements().
 */
function field_upload_elements() {
  $elements = array();

  $elements['field_upload'] = array(
    // FormAPI callbacks;
    '#input' => TRUE,
    '#value_callback' => 'field_upload_value',
    '#element_validate' => array('field_upload_validate'),
    '#process' => array('field_upload_process'),
    '#after_build' => array('field_upload_after_build'),
    
    // drupal render callbacks 
    '#pre_render' => array('field_upload_pre_render'),

    // element specific callbacks.
    '#size' => 48,
    // @see: file_save_upload validator callbacks.
    '#validators' => array(),
    // @see: file_save_upload destination argument.
    '#dest' => file_directory_path(),
  );  

  return $elements;
}

/** 
 * field_upload value callback, we do a little cheating here and alter
 * out element just a little bit. ;)
 */
function field_upload_value(&$element, $edit = null) {
  if (!is_null($edit)) {
    // we may get something here if we have a value.
  }
  // check _FILES since edit will always be null for file uploads.
  if (empty($_FILES['files']['name'][$element['#name']])) {
    dsm('field_upload_value::default_value');
    return (array)$element['#default_value'];
  }  
  dsm('field_upload_value::real_value');
  return (array)file_save_upload($element['#name'], $element['#validators'], $element['#dest']);
}


function field_upload_process(&$element, $edit, $state, $form) {
  dsm('field_upload_process');
  // make sure the form can accept uploads.  
  $form['#attributes']['enctype'] = 'multipart/form-data';
  // If the element as a value.. spawn out elements for the files properties.
  if ($element['#value']) {
     $file = $element['#value'];
     $element['#tree'] = true;
     $element['#theme'] = 'field_file';
     $element['filename'] = array(
        '#title' => t('filename'),
        '#type' => 'textfield',
        '#default_value' => $file['filename'],
     );
     $owner = user_load($file['uid']);
     $element['owner'] = array(
        '#title' => t('owner'),
        '#type' => 'textfield',
        '#default_value' => $owner->name,
        '#autocomplete_path' => 'user/autocomplete',
     );   
     $element['status'] = array(
        '#title' => t('status'),
        '#type' => 'select',
        '#options' => array(0 => t('temporary'), 1 => t('permanent')),
        '#default_value' => $file['status'],
     );
     $element['delete'] = array(
        '#title' => 'delete',
        '#type' => 'button',
     );   
     // do i need to add the addition file properties?
  }  
  //dsm($element);
  dsm($element);
  return $element;
}

function field_upload_after_build($element, $state) {
 dsm('field_upload_after_build');
 return $element;
}


function field_upload_validate($element, $state, $form){
  dsm('field_upload_validate');
}  

function theme_field_upload($element) {
  dsm('theme_field_upload');
  _form_set_class($element, array('form-file'));
  return theme('form_element', $element, '<input type="file" name="files['. $element['#name'] .']"'. ($element['#attributes'] ? ' '. drupal_attributes($element['#attributes']) : '') .' id="'. $element['#id'] .'" size="'. $element['#size'] .'" accept="'. $element['#accept'] ."\" />\n");
}
 
function theme_field_file($element) {
  foreach(element_children($element) as $child) {
    $output .= drupal_render($element[$child]);
  }  
  return $output;
  return drupal_render($element);
}

function field_upload_form($state) {
  $form = array('#attributes' => array('enctype' => 'multipart/form-data'));
  $form['upload'] = array(
    '#title' => t('Upload'),
    '#type' => 'field_upload',
    '#default_value' => field_file_load(17),
    '#accept' => 'image/jpg, image/gif, image/png',
    '#maxfilesize' => '8M',
  );
  $form['submit'] = array('#type' => 'submit', '#name' => 'submit', '#value' => 'submit');
  return $form;
}

function filed_upload_form_alter($id, $form) {
  dsm('alter '. $id);
}

function field_upload_form_validate() {
  dsm('field_upload_form_validate');
  //dsm(func_get_args());
}

function field_upload_form_submit($form, &$state) {
  dsm('field_upload_form_submit');
  //dsm($form);
  //dsm($state);
}
