<?php
// $Id$

/**
 * @file
 * Adds extra functionality to FileFields Path settings.
 */

/**
 * Implementation of hook_form_alter().
 */
function filefield_paths_form_alter(&$form, $form_state, $form_id) {
  if (preg_match('/[filefield|image]/', $form['basic']['type']['#value']) && isset($form['widget']['path_settings'])) {
    unset($form['widget']['path_settings']['file_path']['#suffix']);

    // Create file name field
    $form['widget']['path_settings']['file_name'] = array(
      '#type' => 'textfield',
      '#title' => 'File name',
      '#default_value' => variable_get(
        'filefield_paths_'. $form['type_name']['#value'] .'_'. $form['field_name']['#value'] .'_file_name',
        '[filefield_paths-name].[filefield_paths-ext]'
      ),
      '#weight' => 2
    );

    $fields = array(
      'file_path' => array(
        'title' => 'File path',
        'weight' => 0
      ),
      'file_name' => array(
        'title' => 'File name',
        'weight' => 2
      )
    );

    foreach ($fields as $field => $data) {
      // Replacement patterns for field
      $form['widget']['path_settings'][$field .'_tokens'] = array(
        '#type' => 'fieldset',
        '#title' => $data['title'] .' replacement patterns',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#description' => $field == 'file_name' ? theme('token_help', 'field') . theme('token_help', 'node') : theme('token_help', 'node'),
        '#weight' => $data['weight']
      );

      $form['widget']['path_settings'][$field .'_cleanup'] = array(
        '#type' => 'fieldset',
        '#title' => $data['title'] .' cleanup settings',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#weight' => $data['weight'] + 1
      );

      // Cleanup field with Pathauto module
      if (module_exists('pathauto')) {
        $form['widget']['path_settings'][$field .'_cleanup'][$field .'_pathauto'] = array(
          '#type' => 'checkbox',
          '#title' => 'Cleanup using Pathauto.',
          '#default_value' => variable_get(
            'filefield_paths_'. $form['type_name']['#value'] .'_'. $form['field_name']['#value'] .'_'. $field .'_pathauto',
            0
          ),
          '#description' => 'Cleanup '. $data['title'] .' using '. l('Pathauto settings', 'admin/build/path/pathauto')
        );
      }

      // Convert field to lower case
      $form['widget']['path_settings'][$field .'_cleanup'][$field .'_tolower'] = array(
        '#type' => 'checkbox',
        '#title' => 'Convert to lower case.',
        '#default_value' => variable_get(
          'filefield_paths_'. $form['type_name']['#value'] .'_'. $form['field_name']['#value'] .'_'. $field .'_tolower',
          0
        ),
        '#description' => 'Convert '. $data['title'] .' to lower case.'
      );

      // Transliterate field with Transliteration module
      if (module_exists('transliteration')) {
        $form['widget']['path_settings'][$field .'_cleanup'][$field .'_transliterate'] = array(
          '#type' => 'checkbox',
          '#title' => 'Transliterate.',
          '#default_value' => variable_get(
            'filefield_paths_'. $form['type_name']['#value'] .'_'. $form['field_name']['#value'] .'_'. $field .'_transliterate',
            0
          ),
          '#description' => 'Transliterate '. $data['title'] .'.'
        );
      }

    }

    $form['#submit'][] = 'filefield_paths_form_submit';
  }
}

/**
 * Implementation of hook_form_submit().
 */
function filefield_paths_form_submit($form, &$form_state) {
  $fields = array('file_path', 'file_name');

  variable_set(
    'filefield_paths_'. $form['type_name']['#value'] .'_'. $form['field_name']['#value'] .'_file_name',
    $form_state['values']['file_name']
  );

  foreach ($fields as $field) {

    variable_set(
      'filefield_paths_'. $form['type_name']['#value'] .'_'. $form['field_name']['#value'] .'_'. $field .'_tolower',
      $form_state['values'][$field .'_tolower']
    );

    if (module_exists('pathauto')) {
      variable_set(
        'filefield_paths_'. $form['type_name']['#value'] .'_'. $form['field_name']['#value'] .'_'. $field .'_pathauto',
        $form_state['values'][$field .'_pathauto']
      );
    }

    if (module_exists('transliteration')) {
      variable_set(
        'filefield_paths_'. $form['type_name']['#value'] .'_'. $form['field_name']['#value'] .'_'. $field .'_transliterate',
        $form_state['values'][$field .'_transliterate']
      );
    }

  }
}

/**
 * Implementation of hook_nodeapi().
 */
function filefield_paths_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

  switch ($op) {
    case 'presave':
      $content_type = content_types($node->type);

      foreach ($content_type['fields'] as $field) {
        if (preg_match('/[filefield|image]/', $field['type']) && is_array($node->$field['field_name'])) {

          foreach ($node->$field['field_name'] as $count => &$file) {
            if (empty($file['filepath'])) {
              continue;
            }

            // If file is newly uploaded, flag to be processed
            if ($file['status'] == 0) {
              $file['data']['process'] = TRUE;
            }
          }

        }
      }
      break;

    case 'insert':
    case 'update':
      $content_type = content_types($node->type);
      $update = FALSE;

      foreach ($content_type['fields'] as $field) {
        if (preg_match('/[filefield|image]/', $field['type']) && is_array($node->$field['field_name'])) {

          // Set base for FileField Paths variables
          $settings['filepath'] = 'filefield_paths_'. $node->type .'_'. $field['field_name'] .'_file_path';
          $settings['filename'] = 'filefield_paths_'. $node->type .'_'. $field['field_name'] .'_file_name';

          foreach ($node->$field['field_name'] as $count => $file) {
            if (empty($file['filepath']) || empty($file['data']['process'])) {
              continue;
            }

            // Process filepath
            $dest = filefield_paths_process_string($file['filepath'], 'node', $node, $settings['filepath']);

            // Process filename
            $file_rename = FALSE;
            if (($filename = variable_get($settings['filename'], '')) != '') {
              $filename = filefield_paths_process_string($filename, 'node', $node, $settings['filename']);
              $filename = filefield_paths_process_string($filename, 'field', array(0 => $file), $settings['filename']);

              if ($file['filename'] != $filename) {
                $file['filename'] = $filename;
                $file_rename = TRUE;
              }
            }

            // Finalize files if necessary
            if ($dest != $file['filepath'] || $file_rename) {
              if (filefield_paths_file_move($file, drupal_substr($dest, 0, strrpos($dest, '/')))) { 

                // Fix reference to old paths in Body and Teaser
                // @TODO: allow for CCK fields
                $body = urldecode(preg_replace('/'. urlencode($file['filepath']) .'/', urlencode($dest), urlencode(urldecode($node->body))));
                $teaser = urldecode(preg_replace('/'. urlencode($file['filepath']) .'/', urlencode($dest), urlencode(urldecode($node->teaser))));
  
                if ($body != $node->body || $teaser != $node->teaser) {
                  $node->body = $body;
                  $node->teaser = $teaser;
  
                  $update = TRUE;
                }

                // Move ImageField thumbnail
                if ($field['type'] == 'image') {
                  file_move(
                    imagefield_file_admin_thumb_path($file),
                    imagefield_file_admin_thumb_path(
                      array('filepath' => drupal_substr($dest, 0, strrpos($dest, '/') + 1) . $file['filename'])
                    ),
                    FILE_EXISTS_RENAME
                  );
                }

              }
            }

          }

          // Cleanup temporary paths
          $paths = explode('/', $field['widget']['file_path']);
          $depth = sizeof($paths);

          for ($count = 0; $count < $depth; $count++) {
            if (sizeof(file_scan_directory(file_directory_path() .'/'. implode('/', $paths), '.*')) == 0) {
              // Directory is empty, delete it.
              @rmdir(file_directory_path() .'/'. implode('/', $paths));

              array_pop($paths);
            }
            else {
              // Directory is not empty, don't delete it.
              break;
            }
          }

        }
      }

      // Re-write node entry if required
      if ($update == TRUE) {
        drupal_write_record('node', $node, 'nid');
        if (!empty($node->revision)) {
          _node_save_revision($node, $user->uid);
          db_query('UPDATE {node} SET vid = %d WHERE nid = %d', $node->vid, $node->nid);
        }
        else {
          _node_save_revision($node, $user->uid, 'vid');
          $update_node = FALSE;
        }
      }

      break;
  }
}

/**
 * Implementation of hook_token_list().
 */
function filefield_paths_token_list($type = 'all') {
  if ($type == 'field' || $type == 'all') {
    $tokens = array();
    $tokens['file']['filefield_paths-name']   = t("File name");
    $tokens['file']['filefield_paths-ext']    = t("File extension");
    return $tokens;
  }
}

/**
 * Implementation of hook_token_values().
 */
function filefield_paths_token_values($type, $object = NULL) {
  if ($type == 'field') {
    $item = $object[0];
    $tokens['filefield_paths-name']           = drupal_substr($item['filename'], 0, strrpos($item['filename'], '.'));
    $tokens['filefield_paths-ext']            = drupal_substr($item['filename'], strrpos($item['filename'], '.') + 1);
    return $tokens;
  }
}

/**
 * Process and cleanup strings.
 */
function filefield_paths_process_string($original, $type = 'global', $object = NULL, $settings) {

  // Process string tokens via Pathauto module
  if (module_exists('pathauto') && variable_get($settings .'_pathauto', 0)) {
    $placeholders = pathauto_get_placeholders($type, $object);
    $value = str_replace($placeholders['tokens'], $placeholders['values'], $original);
  }

  // Process string tokens via Token module
  else {
    $value = token_replace($original, $type, $object);
  }

  // Transliterate string
  if (module_exists('transliteration') && variable_get($settings .'_transliterate', 0)) {
    $value = transliteration_get($value);
    if ($type == 'field') {
      $value = transliteration_clean_filename($value);
    }
  }

  // Convert string to lower case
  if (variable_get($settings .'_tolower', 0) || (variable_get($settings .'_pathauto', 0) && variable_get('pathauto_case', 0))) {
    // Convert string to lower case
    $value = drupal_strtolower($value);
  }

  return $value;
}

/**
 * Move file and update its database record.
 */
function filefield_paths_file_move($source, $dest, $replace = FILE_EXISTS_RENAME) {
  $dest = field_file_strip_path($dest);

  foreach (explode('/', $dest) as $dir) {
    $dirs[] = $dir;
    $path = file_create_path(implode($dirs, '/'));
    if (!field_file_check_directory($path, FILE_CREATE_DIRECTORY, $form_item)) {
      watchdog('filefield_paths', t('FileField Paths failed to create directory (%d).', array('%d' => $path)), WATCHDOG_ERROR);
      return FALSE;
    }
  }

  if (!file_move($source['filepath'], $dest .'/'. $source['filename'], $replace)) {
    watchdog('filefield_paths', t('FileField Paths failed to move file (%o) to (%n).', array('%o' => $source_date['filepath'], '%n' => $dest .'/'. $source_date['filename'])), WATCHDOG_ERROR);
    return FALSE;
  }

  db_query('UPDATE {files} SET filename = "%s", filepath = "%s" WHERE fid = %d', $source['filename'], $source['filepath'], $source['fid']);

  return TRUE;
}
