<?php
// $Id$

/**
 * @file
 * Adds extra functionality to FileFields Path settings.
 */

/**
 * Implementation of hook_menu().
 */
function filefield_paths_menu() {
  $items['filefield_paths/alias/%'] = array(
    'page callback' => 'filefield_paths_file_alias',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function filefield_paths_form_alter(&$form, $form_state, $form_id) {

  // Set variables for FileField.module
  if (preg_match('/\bfilefield\b|\bimage\b/', $form['basic']['type']['#value']) && isset($form['widget']['path_settings'])) {
    $ffp = array(
      'show' => TRUE,
      'type' => $form['type_name']['#value'],
      'name' => $form['field_name']['#value'],
      'form_path' => &$form['widget']['path_settings'],
      'file_path_default' => $form['widget']['path_settings']['file_path']['#default_value']
    );

    unset($form['widget']['path_settings']['file_path']['#suffix']);
  }

  // Set variables for Upload.module
  elseif (module_exists('upload') && $form['#id'] == 'node-type-form') {
    $ffp = array(
      'show' => TRUE,
      'type' => $form['#node_type']->type,
      'name' => 'upload',
      'form_path' => &$form['workflow']['path_settings'],
      'file_path_default' => ''
    );

    // Create path settings fieldset
    $ffp['form_path'] = array(
      '#type' => 'fieldset',
      '#title' => 'Path settings',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE
    );

    $ffp['form_path']['file_path'] = array(
      '#type' => 'textfield',
      '#title' => 'File path',
      '#description' => t('Optional subdirectory within the "%dir" directory where files will be stored. Do not include trailing slash.', array('%dir' => variable_get('file_directory_path', 'files')))
    );
  }

  if ($ffp['show'] == TRUE) {
    $result = db_fetch_object(
      db_query("SELECT filename, filepath, filealias FROM {filefield_paths} WHERE type = '%s' AND field = '%s'",
      $ffp['type'], $ffp['name'])
    );

    if (!empty($result)) {
      $settings = array(
        'file_path' => unserialize($result->filepath),
        'file_name' => unserialize($result->filename),
        'file_alias' => unserialize($result->filealias)
      );
    }

    // Create file name field
    $ffp['form_path']['file_name'] = array(
      '#type' => 'textfield',
      '#title' => 'File name',
      '#default_value' => isset($settings['file_name']['value'])
        ? $settings['file_name']['value']
        : '[filefield_paths-name].[filefield_paths-ext]'
      ,
      '#weight' => 2
    );

    if (module_exists('path')) {
      // Create file alias field
      $ffp['form_path']['file_alias'] = array(
        '#type' => 'textfield',
        '#title' => 'File alias',
        '#default_value' => isset($settings['file_alias']['value'])
          ? $settings['file_alias']['value']
          : ''
        ,
        '#weight' => 5
      );

      $ffp['form_path']['file_alias_display'] = array(
        '#type' => 'checkbox',
        '#title' => 'Display alias',
        '#description' => 'If checked, the file alias will be displayed instead of the file.',
        '#default_value' => isset($settings['file_alias']['display'])
          ? $settings['file_alias']['display']
          : 0
        ,
        '#weight' => 8
      );
    }

    $fields = array(
      'file_path' => array(
        'title' => 'File path',
        'display' => TRUE,
        'default' => $ffp['file_path_default'],
        'weight' => 0
      ),
      'file_name' => array(
        'title' => 'File name',
        'display' => TRUE,
        'default' => '[filefield_paths-name].[filefield_paths-ext]',
        'weight' => 3
      ),
      'file_alias' => array(
        'title' => 'File alias',
        'display' => module_exists('path'),
        'default' => '',
        'weight' => 6
      )
    );

    foreach ($fields as $field => $data) {
      if (!$data['display']) {
        continue;
      }

      // Set defualt value for patterns
      $ffp['form_path'][$field]['#default_value'] = isset($settings[$field]['value'])
        ? $settings[$field]['value']
        : $data['default'];

      // Replacement patterns for field
      $ffp['form_path'][$field .'_tokens'] = array(
        '#type' => 'fieldset',
        '#title' => $data['title'] .' replacement patterns',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#description' => theme('token_help', 'field') . theme('token_help', 'node'),
        '#weight' => $data['weight']
      );

      $ffp['form_path'][$field .'_cleanup'] = array(
        '#type' => 'fieldset',
        '#title' => $data['title'] .' cleanup settings',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#weight' => $data['weight'] + 1
      );

      // Cleanup field with Pathauto module
      $ffp['form_path'][$field .'_cleanup'][$field .'_pathauto'] = array(
        '#type' => 'checkbox',
        '#title' => 'Cleanup using Pathauto.',
        '#default_value' => isset($settings[$field]['pathauto'])
          ? $settings[$field]['pathauto']
          : 0
        ,
        '#description' => 'Cleanup '. $data['title'] .' using '. l('Pathauto settings', 'admin/build/path/pathauto')
      );
      if (!module_exists('pathauto')) {
        $ffp['form_path'][$field .'_cleanup'][$field .'_pathauto']['#disabled'] = TRUE;
        $ffp['form_path'][$field .'_cleanup'][$field .'_pathauto']['#default_value'] = 0;
      }

      // Convert field to lower case
      $ffp['form_path'][$field .'_cleanup'][$field .'_tolower'] = array(
        '#type' => 'checkbox',
        '#title' => 'Convert to lower case.',
        '#default_value' => isset($settings[$field]['tolower'])
          ? $settings[$field]['tolower']
          : 0
        ,
        '#description' => 'Convert '. $data['title'] .' to lower case.'
      );

      // Transliterate field with Transliteration module
      $ffp['form_path'][$field .'_cleanup'][$field .'_transliterate'] = array(
        '#type' => 'checkbox',
        '#title' => 'Transliterate.',
        '#default_value' => isset($settings[$field]['transliterate'])
          ? $settings[$field]['transliterate']
          : 0
        ,
        '#description' => 'Transliterate '. $data['title'] .'.'
      );
      if (!module_exists('transliteration')) {
        $ffp['form_path'][$field .'_cleanup'][$field .'_transliterate']['#disabled'] = TRUE;
        $ffp['form_path'][$field .'_cleanup'][$field .'_transliterate']['#default_value'] = 0;
      }

    }

    $form['#submit'][] = 'filefield_paths_form_submit';
  }
}

/**
 * Implementation of hook_form_submit().
 */
function filefield_paths_form_submit($form, &$form_state) {

  // Set variables for FileField.module
  if ($form_state['values']['form_id'] != 'node_type_form') {
    $ffp = array(
      'type' => $form_state['values']['type_name'],
      'name' => $form_state['values']['field_name']
    );
  }

  // Set variables for Upload.module
  else {
    $ffp = array(
      'type' => $form_state['values']['type'],
      'name' => 'upload'
    );
  }

  $settings = array(
    'filename' => array(
      'value' => $form_state['values']['file_name'],
      'tolower' => $form_state['values']['file_name_tolower'],
      'pathauto' => $form_state['values']['file_name_pathauto'],
      'transliterate' => $form_state['values']['file_name_transliterate']
    ),
    'filepath' => array(
      'value' => $form_state['values']['file_path'],
      'tolower' => $form_state['values']['file_path_tolower'],
      'pathauto' => $form_state['values']['file_path_pathauto'],
      'transliterate' => $form_state['values']['file_path_transliterate']
    )
  );

  if (module_exists('path')) {
    $settings['filealias'] = array(
      'value' => $form_state['values']['file_alias'],
      'tolower' => $form_state['values']['file_alias_tolower'],
      'pathauto' => $form_state['values']['file_alias_pathauto'],
      'transliterate' => $form_state['values']['file_alias_transliterate'],
      'display' => $form_state['values']['file_alias_display'],
    );
  }

  $result = db_fetch_object(
    db_query("SELECT filename, filepath, filealias FROM {filefield_paths} ".
    "WHERE type = '%s' AND field = '%s'", $ffp['type'], $ffp['name'])
  );

  if (!empty($result)) {
    if (!isset($settings['filealias'])) {
      $settings['filealias'] = unserialize($result->filealias);
    }

    db_query(
      "UPDATE {filefield_paths} SET filename = '%s', filepath = '%s', filealias = '%s' WHERE type = '%s' AND field = '%s'",
      serialize($settings['filename']), serialize($settings['filepath']), serialize($settings['filealias']), $ffp['type'], $ffp['name']
    );
  }

  else {
    if (!isset($settings['filealias'])) {
      $settings['filealias'] = array();
    }

    db_query(
      "INSERT INTO {filefield_paths} (type, field, filename, filepath, filealias) VALUES ('%s', '%s', '%s', '%s')",
      $ffp['type'], $ffp['name'], serialize($settings['filename']), serialize($settings['filepath']), serialize($settings['filealias'])
    );
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function filefield_paths_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

  switch ($op) {
    case 'presave':
      $content_type = content_types($node->type);

      foreach ($content_type['fields'] as $field) {
        if (preg_match('/\bfilefield\b|\bimage\b/', $field['type']) && is_array($node->$field['field_name'])) {

          foreach ($node->$field['field_name'] as $count => &$file) {
            if (empty($file['filepath'])) {
              continue;
            }

            // If file is newly uploaded, flag to be processed
            if ($file['status'] == 0) {
              $file['data']['process'] = TRUE;
            }
          }

        }
      }
      break;

    case 'insert':
    case 'update':
      $update = FALSE;

      if (($ffp = filefield_paths_get_fields($node, $op)) == FALSE) {
        break;
      }

      // Process files
      foreach ($ffp['#files'] as &$file) {
        filefield_paths_process_file($file, $ffp['#settings'][$file['name']], $node, $update);
      }

      // Re-write node entry if required
      if ($update == TRUE) {
        drupal_write_record('node', $node, 'nid');
        if (!empty($node->revision)) {
          _node_save_revision($node, $user->uid);
          db_query('UPDATE {node} SET vid = %d WHERE nid = %d', $node->vid, $node->nid);
        }
        else {
          _node_save_revision($node, $user->uid, 'vid');
        }
      }

      // Cleanup temporary paths
      if ($ffp['#settings']) {
        foreach ($ffp['#settings'] as $field) {
          $paths = explode('/', $field['filepath']['value']);

          while ($paths) {
            if (@rmdir(file_directory_path() .'/'. implode('/', $paths)) === TRUE) {
              array_pop($paths);
              continue;
            }
            break;
          }
        }
      }

      break;

    case 'load':
      if (($ffp = filefield_paths_get_fields($node, $op)) == FALSE) {
        break;
      }

      foreach ($ffp['#files'] as &$file) {
        if ($ffp['#settings'][$file['name']]['filealias']['display'] == TRUE) {
          $filefield_paths_alias = 'filefield_paths/alias/'. $file['field']['fid'];
          if (($alias = drupal_get_path_alias($filefield_paths_alias)) != $filefield_paths_alias) {
            foreach (explode('/', file_directory_path()) as $dir) {
              $relative_dir .= '../';
            }

            $file['field']['filepath'] = $relative_dir . $alias;
            $file['field']['filename'] = array_pop(explode('/', $alias));
          }
        }
      }

      break;
  }
}

function filefield_paths_get_fields($node, $op) {
  // Check for FileField.module files
  $content_type = content_types($node->type);

  foreach ($content_type['fields'] as $field) {
    if (preg_match('/\bfilefield\b|\bimage\b/', $field['type']) && is_array($node->$field['field_name'])) {

      foreach ($node->$field['field_name'] as &$file) {
        if ((!empty($file['filepath']) && !empty($file['data']['process'])) || $op == 'load') {
          $ffp['#files'][] = array(
            'field' => &$file,
            'module' => $field['module'],
            'name' => $field['field_name']
          );

          $ffp['#types'][$field['field_name']] = TRUE;
        }
      }

    }
  }

  // Check for Upload.module files
  if ($node->files) {
    foreach ($node->files as &$file) {
      if ($file['new'] == TRUE || $op == 'load') {
        $ffp['#files'][] = array(
          'field' => &$file,
          'module' => 'upload',
          'name' => 'upload'
        );

        $ffp['#types']['upload'] = TRUE;
      }
    }
  }

  if (!is_array($ffp['#types'])) {
    return FALSE;
  }

  // Load fields settings
  foreach ($ffp['#types'] as $field => $temp) {
    $result = db_fetch_object(
      db_query("SELECT filename, filepath, filealias FROM {filefield_paths} WHERE type = '%s' AND field = '%s'", $node->type, $field)
    );

    if (!empty($result)) {
      $ffp['#settings'][$field] = array(
        'filepath' => unserialize($result->filepath),
        'filename' => unserialize($result->filename),
        'filealias' => unserialize($result->filealias)
      );
    }
  }

  return $ffp;
}

function filefield_paths_process_file(&$file, $settings, &$node, &$update) {

  // Process filepath
  $file['filepath']['old'] = $file['field']['filepath'];
  $file['filepath']['new'] = filefield_paths_process_string(file_directory_path() .'/'. $settings['filepath']['value'] .'/'. $file['field']['filename'], 'node', $node, $settings['filepath']);
  $file['filepath']['new'] = filefield_paths_process_string($file['filepath']['new'], 'field', array(0 => $file['field']), $settings['filepath']);

  // Process filename
  $file['filename']['old'] = $file['field']['filename'];
  if (($file['filename']['new'] = $settings['filename']['value']) != '') {
    $file['filename']['new'] = filefield_paths_process_string($file['filename']['new'], 'node', $node, $settings['filename']);
    $file['filename']['new'] = filefield_paths_process_string($file['filename']['new'], 'field', array(0 => $file['field']), $settings['filename']);
  }
  else {
    $file['filename']['new'] = $file['field']['filename'];
  }

  // Finalize files if necessary
  if (dirname($file['filepath']['new']) != dirname($file['field']['filepath']) || $file['filename']['new'] != $file['field']['filename']) {
    if (filefield_paths_file_move($file)) {

      // Fix reference to old paths in Body and Teaser
      // @TODO: allow for CCK fields
      $body = str_replace($file['filepath']['old'],  $file['filepath']['new'], $node->body);
      $teaser = str_replace($file['filepath']['old'],  $file['filepath']['new'], $node->teaser);

      if ($body != $node->body || $teaser != $node->teaser) {
        $node->body = $body;
        $node->teaser = $teaser;

        $update = TRUE;
      }

      // Move ImageField thumbnail
      if ($file['module'] == 'imagefield') {
        file_move(
          imagefield_file_admin_thumb_path(
            array('filepath' => $file['filepath']['old'])
          ),
          imagefield_file_admin_thumb_path($file['field']),
          FILE_EXISTS_RENAME
        );
      }

      // Store new filename in file Array
      $file['field']['filename'] = $file['filename']['new'];
    }
  }

  if (module_exists('path')) {
    // Process filealias
    $file['filealias'] = filefield_paths_process_string($settings['filealias']['value'], 'node', $node, $settings['filealias']);
    $file['filealias'] = filefield_paths_process_string($file['filealias'], 'field', array(0 => $file['field']), $settings['filealias']);

    path_set_alias('filefield_paths/alias/'. $file['field']['fid'], $file['filealias']);
  }
}

/**
 * Implementation of hook_token_list().
 */
function filefield_paths_token_list($type = 'all') {
  if ($type == 'field' || $type == 'all') {
    $tokens = array();
    $tokens['file']['filefield_paths-name'] = t("File name");
    $tokens['file']['filefield_paths-ext'] = t("File extension");
    return $tokens;
  }
}

/**
 * Implementation of hook_token_values().
 */
function filefield_paths_token_values($type, $object = NULL) {
  if ($type == 'field') {
    $item = pathinfo($object[0]['filename']);
    $tokens['filefield_paths-name'] = $item['filename'];
    $tokens['filefield_paths-ext'] = $item['extension'];
    return $tokens;
  }
}

/**
 * Process and cleanup strings.
 */
function filefield_paths_process_string($original, $type, $object, $settings) {

  // Process string tokens via Pathauto module
  if (module_exists('pathauto') && $settings['pathauto']) {
    $placeholders = pathauto_get_placeholders($type, $object);
    $value = str_replace($placeholders['tokens'], $placeholders['values'], $original);
  }

  // Process string tokens via Token module
  else {
    $value = token_replace($original, $type, $object);
  }

  // Transliterate string
  if (module_exists('transliteration') && $settings['transliterate']) {
    $value = transliteration_get($value);
    if ($type == 'field') {
      $value = transliteration_clean_filename($value);
    }
  }

  // Convert string to lower case
  if ($settings['tolower'] || ($settings['pathauto'] && variable_get('pathauto_case', 0))) {
    // Convert string to lower case
    $value = drupal_strtolower($value);
  }

  return $value;
}

/**
 * Move file and update its database record.
 */
function filefield_paths_file_move(&$file, $replace = FILE_EXISTS_RENAME) {
  $dest = field_file_strip_path(dirname($file['filepath']['new']));

  foreach (explode('/', $dest) as $dir) {
    $dirs[] = $dir;
    $path = file_create_path(implode($dirs, '/'));
    if (!field_file_check_directory($path, FILE_CREATE_DIRECTORY, $form_item)) {
      watchdog('filefield_paths', 'FileField Paths failed to create directory (%d).', array('%d' => $path), WATCHDOG_ERROR);
      return FALSE;
    }
  }

  if (!file_move($file['field']['filepath'], $dest .'/'. $file['filename']['new'], $replace)) {
    watchdog('filefield_paths', 'FileField Paths failed to move file (%o) to (%n).', array('%o' => $file['filepath']['old'], '%n' => $dest .'/'. $file['filename']['new']), WATCHDOG_ERROR);
    return FALSE;
  }

  db_query('UPDATE {files} SET filename = "%s", filepath = "%s" WHERE fid = %d', $file['filename']['new'], $file['field']['filepath'], $file['field']['fid']);

  return TRUE;
}

function filefield_paths_file_alias($fid) {
  if ($_SERVER[REQUEST_URI] == '/filefield_paths/alias/'. $fid) {
    drupal_not_found();
    exit;
  }

  $result = db_fetch_object(db_query("SELECT filemime, filepath FROM {files} WHERE fid = %d", $fid));

  header('Content-Type: '. $result->filemime);
  readfile($result->filepath);
}
