<?php
//$Id$

/**
 * Implementation of hook_help().
 */
function globalredirect_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('This module will do a 301 redirect for all nodes which have an alias but are not using that alias.');
  }
}


/**
 * Implementation of hook_init().
 */
function globalredirect_init() {
  if(isset($_REQUEST['q']) && function_exists('drupal_get_path_alias') && !isset($_REQUEST['destination'])) {
    
    // Get the Query String (minus the 'q'). If none set, set to NULL
    $query_string = drupal_query_string_encode($_GET, array('q'));
    if (empty($query_string)) {
      $query_string = NULL;
    }

    // If current path is also the frontpage, redirect to http://www.mysite.com.
    if(drupal_is_front_page()) {
      drupal_goto('', $query_string, NULL, 301);
    }

    // Get the request string (minus trailing slash e.g. node/123/)
    $request = preg_replace('/\/$/', '', $_REQUEST['q']);
    
    // Check the path (eg, node/123) for an alias. If one is found, redirect.
    if ($alias = drupal_get_path_alias($request)) {
      // If alias is different to the request, redirect...
      if ($alias != $request) {
      drupal_goto($alias, $query_string, NULL, 301);
      }

      // If the request produced by the regex above differs to the urls request, redirect (basically, de-slash)
      if ($request != $_REQUEST['q']) {
        drupal_goto($request, $query_string, NULL, 301);
      }
    }
  }
}
