<?php
// $Id$

/**
 * @file
 * Defines an image field type.
 * imagefield uses content.module to store the fid, and the drupal files
 * table to store the actual file data.
 *
 */

include_once('field_file.inc');
/**
 * @defgroup core_hooks
 * @{
 */

/**
 * Implementation of hook_menu().
 */
function imagefield_menu() {
  $items = array();
  $items['imagefield/js'] = array(
    'page callback' => 'imagefield_js',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function imagefield_perm() {
  return array('view imagefield uploads');
}

/**
 * Implementation of hook_theme().
 */
function imagefield_theme() {
  return array(
    'imagefield_image' => array(
      'arguments' => array('file' => null, 'alt' => '', 'title' => '', 'attributes' => null, 'getsize' => TRUE),
    ),
    'imagefield' => array(
      'arguments' => array('element' => null),
    ),
    'imagefield_row' => array(
      'arguments' => array('element' => null),
    ),
    'imagefield_formatter_image_plain' => array(
      'arguments' => array('element' => null),
    ),
    'imagefield_formatter_image_nodelink' => array(
      'arguments' => array('element' => null),
    ),
    'imagefield_formatter_image_imagelink' => array(
      'arguments' => array('element' => null),
    ),
    'imagefield_formatter_url_plain' => array(
      'arguments' => array('element' => null),
    ),
    'imagefield_formatter_path_plain' => array(
      'arguments' => array('element' => null),
    ),
  );
}

/**
 * Implementation of hook_elements().
 */
function imagefield_elements() {
  $elements = array();
  $elements['imagefield_widget_default'] =  array(
    '#input' => TRUE,
    '#columns' => array('fid', 'title', 'alt'),
    '#process' => array('imagefield_element_process'),
    '#tree' => TRUE,
    '#description' => t('Changes made to the attachments are not permanent until you save this post.'),
  );
  return $elements;
}

/**
 * Process the image type element before displaying the field.
 */
function imagefield_element_process($element, $edit, &$form_state, $form) {
  $field = $element['#field'];
  drupal_add_js(drupal_get_path('module', 'imagefield') .'/imagefield.js');
  drupal_add_css(drupal_get_path('module', 'imagefield') .'/imagefield.css');
  // Pull in form state saved in storage.
  form_get_cache($form_state['values']['form_build_id'], $form_state);
  if (isset($form_state['storage'][$fieldname])) {
    $form_state['values'][$fieldname] = $form_state['storage'][$fieldname];
    // Unset the storage to keep the form from unnecessarily rebuilding.
    unset($form_state['storage'][$fieldname]);
  }
  // Set an internal flag for requiredness. Prevents FAPI from interfering.
  $element['#image_required'] = $element['#required'];
  $element['#required'] = FALSE;
  $files = array();
  if (isset($form_state['values'])) {
    // Set a default value if available.
    if (!isset($form_state[$fieldname]) && isset($element['#default_value'])) {
      $form_state['values'][$fieldname] = $element['#default_value'];
    }
    // @hack: Why is this data not complete before the element is built?
    foreach ($form_state['values'][$fieldname] as $delta => $file) {
      if (!empty($file['fid']))  $files[$file['fid']] = array_merge($file, field_file_load($file['fid']));
    }
  }
  $form_state['values'][$fieldname] = $files;
  $element['#files'] = $files;
  foreach ($files as $fid => $file) {
    $element[$fid]['flags']['delete'] = array(
      '#type' => 'checkbox',
      '#title' => t('Delete'),
      '#default_value' => isset($file['flags']['delete']) ? $file['flags']['delete'] : 0,
    );
    $element[$fid]['admin_preview'] = array(
      '#type' => 'markup',
      '#value' => theme('imagefield_image', $file, $file['alt'], $file['title'], array('width' => '150'), FALSE),
    );
    $element[$fid]['description'] = array(
      '#type' => 'markup',
      '#value' => '<strong>'. t('Filename: ') .'</strong>'. $file['filename'],
    );
    $element[$fid]['alt'] = array(
      '#type' => 'hidden',
      '#value' => $file['filename'],
    );
    // overwrite with an input field if custom_alt is flagged;
    if ($field['widget']['custom_alt']) {
      $element[$fid]['alt'] = array(
        '#type' => 'textfield',
        '#title' =>  t('Alternate text'),
        '#default_value' => $file['alt'],
        '#description' => t('Alternate text to be displayed if the image cannot be displayed.'),
        '#maxlength' => 255,
        '#size' => 10,
      );
    }
    $element[$fid]['title'] = array(
      '#type' => 'hidden',
      '#value' => $file['filename'],
    );
    // overwrite with an input field if custom_title is flagged;
    if ($field['widget']['custom_title']) {
      $element[$fid]['title'] = array(
        '#type' => 'textfield',
        '#title' =>  t('Title'),
        '#default_value' =>  $file['title'],
        '#description' => t('Text to be displayed on mouse overs.'),
        '#maxlength' => 255,
        '#size' => 10,
      );
    }
    if ($file['filepath'] && !empty($file['flags']['hidden'])) {
      // Render all the form values of this item if it is hidden.
      $element[$fid]['title'] = array('#type' => 'value', '#value' => $file['title']);
      $element[$fid]['alt'] = array('#type' => 'value', '#value' => $file['alt']);
      $element[$fid]['flags']['delete'] = array('#type' => 'value', '#value' => !empty($file['flags']['delete']));
    }
    if ($element['#multiple']) {
      $element[$fid]['weight'] = array(
        '#type' => 'weight',
        '#delta' => max('10', count($element['#files'])),
      );
    }
    $element[$fid]['flags']['hidden'] = array('#type' => 'value', '#value' => !empty($file['flags']['hidden']));
    $element[$fid]['filename'] = array('#type' => 'value',  '#value' => $file['filename']);
    $element[$fid]['filepath'] = array('#type' => 'value',  '#value' => $file['filepath']);
    $element[$fid]['filemime'] = array('#type' => 'value',  '#value' => $file['filemime']);
    $element[$fid]['filesize'] = array('#type' => 'value',  '#value' => $file['filesize']);
    $element[$fid]['fid'] = array('#type' => 'hidden',  '#value' => $file['fid']);
  }
  // Special handling for single value fields
  if (!$element['#multiple'] && count($element['#files'])) {
    $element['replace'] = array(
      '#type' => 'markup',
      '#value' => t('If a new image is chosen, the current image will be replaced upon submitting the form.'),
    );
  }
  elseif ($element['#multiple_limit'] != 0 && $element['#multiple_limit'] <= count($element['#files'])) {
    $element['replace'] = array(
      '#type' => 'markup',
      '#value' => format_plural($element['#multiple_limit'], 'You can only attach one image to this field. Delete the image if you wish to be able to upload a different one.', 'You can only attach @count images to this field. Delete an image if you wish to be able to upload different images.'),
    );
  }
  // multiupload: add an add new field button.
  // onchange ajax upload each file input after validation.
  // update date 'file_inputs' with qty of file inputs.
  // name file inputs $fieldname .'_upload_'. number of file input.
  // inprepare form_values hook iterate over each input.
  // can we display files sizes to predict the total size of an upload.
  $extensions_description = empty($field['widget']['file_extensions'])
  ? ''
  : t('<br />Allowed extensions: %ext', array('%ext' => $field['widget']['file_extensions']));
  // Seperate from tree becase of that silly things won't be
  // displayed if they are a child of '#type' = form issue
  $element['new'][$fieldname .'_upload'] = array(
    '#type'  => 'file',
    '#title' => t('Upload a new image'),
    '#description' => $field['widget']['description'] . $extensions_description,
    '#tree' => FALSE,
    '#weight' => 9,
    '#attributes' => array('class' => 'imagefield imagefield-'. $fieldname, 'accept' => str_replace(' ', '|', trim($field['widget']['file_extensions']))),
  );
  $element['new']['upload'] = array(
    '#type' => 'button',
    '#value' => t('Upload'),
    '#ahah' => array(
      'wrapper' => $element['#id'] .'-wrapper',
      'path' => 'imagefield/js/'. $field['type_name'] .'/'. $field['field_name'],
      'progress' => array('type' => 'bar', 'message' => t('Uploading image...')),
    ),
    '#weight' => 10,
  );
  return $element;
}

function _imagefield_widget_validate($element, &$form_state) {
  $field = $element['#field'];
  $fieldname = $field['field_name'];
  $items =& $form_state['values'][$fieldname];
  unset($items['new']);
 
  global $user;
  $widget_image_path = token_replace($field['widget']['image_path'], 'user', $user);

  $validators = array(
    'file_validate_extensions' => array($field['widget']['file_extensions']),
    'file_validate_size' => array($field['widget']['max_filesize']),
    'file_validate_image_resolution' => array($field['widget']['max_resolution']),
  );

  $complete_image_path = file_directory_path() .'/'. $widget_image_path;

  // Attach new files.
  if (imagefield_check_directory($widget_image_path, $fieldname .'_upload') && $file = file_save_upload($fieldname .'_upload', $validators, $complete_image_path)) {
    // If a single field, mark any other images for deletion.
    if (count($items)) {
      foreach ($items as $delta => $item_file) {
        if (!$element['#multiple']) {
          $items[$delta]['flags']['hidden'] = TRUE;
          $items[$delta]['flags']['delete'] = TRUE;
        }
        if (empty($items[$delta]['fid'])) {
          unset($items[$delta]);
        }
      }
    }
    $file = (array)$file;
    $items[$file['fid']] = $file;
 }
 
  // Sum all the items marked for deletion.
  $deleted = 0;
  foreach ($items as $delta => $item) {
    if (is_numeric($delta) && !empty($item['flags']['delete'])) {
      $deleted++;
    }
  }

  // Insure at least one image is going to be saved.
  if ($element['#image_required']) {
    if (!count($items)) {
      form_set_error($field['field_name'] .'_upload', t('@field is required. Please upload an image.', array('@field' => $field['widget']['label'])));
    }
    else if (count($items) == $deleted ) {
      form_set_error($field['field_name'] .'_upload',  t('@field is required. Please uncheck at least one delete checkbox or upload another image.', array('@field' => $field['widget']['label'])));
    }
  }
 
  // Prevent more than the maximum limit.
  if ($element['#multiple'] && $element['#multiple_limit'] != 0 && count($items) - $deleted > $element['#multiple_limit']) {
    form_set_error($field['field_name'] .'_upload', t('You are only allowed to upload up to %maximages images.', array('%maximages' => $element['#multiple_limit'])));
  }
}

/**
 * @} End "defgroup core_hooks"
 */


/**
 * @defgroup cck_hooks
 * @{
 */
/**
 * Implementation of hook_field_info().
 */
function imagefield_field_info() {
  return array(
    'image' => array(
      'label' => t('Image'),
      'description' => t('Store an image file and optionally text for alt and title tags.'),
    ),
  );
}

/**
 * Implementation of hook_field_settings().
 */
function imagefield_field_settings($op, $field) {
  switch ($op) {
    case 'form':
      $form = array();
      $form['default'] = array(
        '#type' => 'fieldset',
        '#title' => t('Default image'),
        '#element_validate' => array('_imagefield_field_settings_default_validate'),
      );
      // Present a thumbnail of the current default image.
      $form['default']['use_default_image'] = array(
        '#type' => 'checkbox',
        '#title' => t('Use default image'),
        '#default_value' =>  $field['use_default_image'],
        '#description' => t('Check here if you want to use a image as default.'),
      );
      if (!empty($field['default_image'])) {
        $form['default']['default_image_thumbnail'] = array(
          '#type' => 'markup',
          '#value' => theme('imagefield_image', $field['default_image'], '', '', array('width' => '150'), false),
        );
      }
      $form['default']['default_image_upload'] = array(
        '#type'  => 'file',
        '#title' => t('Upload image'),
        '#description' => t('Choose a image that will be used as default.'),
      );
      // We set this value on 'validate' so we can get cck to add it
      // as a standard field setting.
      $form['default_image'] = array(
        '#type' => 'value',
        '#value' => $field['default_image'],
      );
      return $form;

    case 'save':
      return array('default_image', 'use_default_image');

    case 'database columns':
      $columns = array(
        'fid' => array('type' => 'int', 'not null' => true, 'default' => '0'),
        'title' => array('type' => 'varchar', 'length' => 255, 'not null' => true, 'default' => '', 'sortable' => true),
        'alt' => array('type' => 'varchar', 'length' => 255, 'not null' => true, 'default' => '', 'sortable' => true),
      );
      return $columns;

    case 'filters':
      return array(
        'not null' => array(
          'operator' => array('=' => t('Has Image')),
          'list' => 'views_handler_operator_yesno',
          'list-type' => 'select',
          'handler' => 'imagefield_views_handler_filter_is_not_null',
        ),
      );
  }
}

/**
 * Element specific validation for imagefield default value.
 *
 * Validated in a separate function from imagefield_field() to get access
 * to the $form_state variable.
 */
function _imagefield_field_settings_default_validate($element, &$form_state) {
  // Verify the destination exists
  $dst = file_directory_path() .'/imagefield_default_images';
  if (!imagefield_check_directory($dst)) {
    form_set_error('default_image', t("The default image could not be uploaded. The destination(%d) does not exist or is not writable by the webserver.", array('%d' => dirname($dst))));
    return;
  }

  // We save the upload here because we can't know the correct
  // file path until we save the file.
  if (!$file = file_save_upload('default_image_upload', array(), $dst)) {
    form_set_error('default_image', t("The default image could not be uploaded. Failed saving to destination(%d).", array('%d' => $dst)));
    return;
  }

  // set new value.
  $form_state['values']['default_image'] = (array)$file;

  // remove old image & clean up database.
  if (file_delete(file_create_path($field['default_image']['filepath']))) {
    db_query('DELETE FROM {files} WHERE fid=%d', $field['default_image']['fid']);
  }
}

/**
 * Custom filter for imagefield NOT null.
 */
function imagefield_views_handler_filter_is_not_null($op, $filter, $filterinfo, &$query) {
  if ($op == 'handler') {
    $query->ensure_table($filterinfo['table']);
    if ($filter['value']) {
      $qs = '%s.%s > 0';
      $query->add_where($qs, $filterinfo['table'], $filterinfo['field']);
    }
    else {
      $qs = '%s.%s = 0 OR %s.%s IS null';
      $query->add_where($qs, $filterinfo['table'], $filterinfo['field'], $filterinfo['table'], $filterinfo['field']);
    }
  }

}

/**
 * Implementation of hook_field().
 */
function imagefield_field($op, $node, $field, &$items, $teaser, $page) {
  $fieldname = $field['field_name'];
  switch ($op) {
    // called after content.module loads default data.
    case 'load':
      if (empty($items)) return;
      foreach ($items as $delta => $item) {
        $items[$delta] = array_merge($item, field_file_load($item['fid']));
      }
      $items = array_values(array_filter($items)); // compact deltas
      return array($fieldname => $items);
      break;

    // called before content.module inserts data.
    case 'insert':
    case 'update':
      foreach ($items as $delta => $item) {
        $items[$delta] = field_file_save($node, $item);
      }
      $items = array_values(array_filter($items)); // compact deltas
      break;

    case 'delete revision':
      foreach ($items as $delta => $item) {
        if (field_file_delete($item)) $items[$delta] = array();
      }
      $items = array_values($items); // compact deltas
      break;
    
    case 'delete':
      foreach ($items as $delta => $item) {
        _imagefield_file_delete($item, true);
      }
      break;

    case 'sanitize':
      foreach ($items as $delta => $item) {
        // Cleanup $items during node preview.
        if (empty($item['fid']) || !empty($item['flags']['delete']) || !empty($item['flags']['hidden'])) {
          unset($items[$delta]);
        }
        // Load the complete file if a filepath is not available.
        if (!empty($item['fid']) && empty($item['filepath'])) {
          $items[$delta] = array_merge($item, _imagefield_file_load($item['fid']));
        }
        // Add nid so formatters can create a link to the node.
        $items[$delta]['nid'] = $node->nid;
      }
      // If completely empty, check for a default image.
      if (empty($items) && $field['use_default_image'] && $field['default_image']['fid']) {
        $items[$field['default_image']['fid']] = $field['default_image'];
        $items[$field['default_image']['fid']] = $node->nid;
      }
      break;
  }
}

/**
 * Implementation of hook_file.
 *
 * Filefield and Imagefield implement hook_file for D6 in their own API's.
 */
function imagefield_file($op, $file) {
  switch ($op) {
    // report references to prevent deletion of files associated to older revisions
    // or by other fields.
    case 'references':
      $references = 0;
      foreach(content_fields() as $field) {
        if (!$field['type'] != 'image') continue;
        $db_info = content_database_info($field);
        $references += db_result(db_query("SELECT count(fid) FROM {%s} WHERE %s=%d", $db_info['table'],  $db_info['columns']['fid']['column'], $item['fid']));
      }
      return array('imagefield' => $references);
  } 
}




/**
 * Implementation of hook_widget_info().
 */
function imagefield_widget_info() {
  return array(
    'imagefield_widget_default' => array(
      'label' => t('Image'),
      'field types' => array('image'),
      'multiple values' => CONTENT_HANDLE_MODULE,
      'callbacks' => array('default value' => CONTENT_CALLBACK_CUSTOM),
    ),
  );
}

/**
 * Implementation of hook_widget_settings().
 */
function imagefield_widget_settings($op, $widget) {
  switch ($op) {
    case 'form':
      $form = array();
      $form['max_resolution'] = array(
        '#type' => 'textfield',
        '#title' => t('Maximum resolution for Images'),
        '#default_value' => $widget['max_resolution'] ? $widget['max_resolution'] : 0,
        '#size' => 15,
        '#maxlength' => 10,
        '#description' =>
        t('The maximum allowed image size expressed as WIDTHxHEIGHT (e.g. 640x480). Set to 0 for no restriction. If a larger image is uploaded, it will be resized to reflect the given width and height.'),
      );
      $form['max_filesize'] = array(
        '#type' => 'textfield',
        '#title' => t('Maximum filesize for Images'),
        '#default_value' => $widget['max_filesize'] ? $widget['max_filesize'] : 0,
        '#size' => 6,
        '#description' => t('The maximum allowed image file size expressed in kilobytes. Set to 0 for no restriction.')
      );
      $form['image_path'] = array(
        '#type' => 'textfield',
        '#title' => t('Image path'),
        '#default_value' => $widget['image_path'] ? $widget['image_path'] : '',
        '#description' => t('Optional subdirectory within the "%dir" directory where images will be stored. Do not include trailing slash. You can use the following tokens in the image path.', array('%dir' => variable_get('file_directory_path', 'files'))),
        '#element_validate' => '_imagefield_widget_settings_image_path_validate', 
        '#suffix' => theme('token_help', 'user'),
      );

      $form['file_extensions'] = array(
        '#type' => 'textfield',
        '#title' => t('Permitted upload file extensions.'),
        '#default_value' => $widget['file_extensions'] ? $widget['file_extensions'] : 'jpg jpeg png gif',
        '#size' => 64,
        '#maxlength' => 64,
        '#description' => t('Extensions a user can upload to this field. Seperate extensions with a space and do not include the leading dot.')
      );

      $form['custom_alt'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable custom alternate text'),
        '#default_value' =>  $widget['custom_alt'] ? $widget['custom_alt'] : 0,
        '#description' => t('Enable custom alternate text for images. Filename will be used if not checked.'),
      );
      $form['custom_title'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable custom title text'),
        '#default_value' =>  $widget['custom_title'] ? $widget['custom_title'] : 0,
        '#description' => t('Enable custom title text for images. Filename will be used if not checked.'),
      );
      return $form;

    case 'save':
      return array('max_resolution', 'max_filesize', 'image_path', 'file_extensions', 'custom_alt', 'custom_title');
  }
}

function _imagefield_widget_settings_image_path_validate($element, &$form_state) {
  // Strip slashes from the beginning and end of $widget['image_path']
  $form_state['values']['image_path'] =  trim($form_state['values']['image_path'], '\\/');
}

/**
 * Implementation of hook_form_alter(). Set the appropriate
 * attibutes to allow file uploads on the field settings form.
 */
function _imagefield_content_admin_field_form_alter(&$form, $form_state, $form_id) {
  $form['#attributes'] = array('enctype' => 'multipart/form-data');
}

/**
 * Create the image directory relative to the 'files' dir recursively for every
 * directory in the path.
 *
 * @param $directory
 *   The directory path under files to check, such as 'photo/path/here'
 * @param $form_element
 *   A form element to throw an error on if the directory is not writable
 */
function imagefield_check_directory($directory, $fieldname = NULL) {
  foreach (explode('/', $directory) as $dir) {
    $dirs[] = $dir;
    $path = file_create_path(implode($dirs, '/'));
    if (!file_check_directory($path, FILE_CREATE_DIRECTORY, $fieldname)) {
      watchdog('imagefield', t('Imagefield failed to create directory(%d) at (%p).', array('%d' => $directory, '%p' => $path)), WATCHDOG_ERROR);
      return false;
    }
  }
  return true;
}

function _imagefield_scale_image($file, $resolution = 0) {
  $info = image_get_info($file['filepath']);
  if ($info) {
    list($width, $height) = explode('x', $resolution);
    if ($width && $height) {
      $result = image_scale($file['filepath'], $file['filepath'], $width, $height);
      if ($result) {
        $file['filesize'] = filesize($file['filepath']);
        drupal_set_message(t('The image %filename was resized to fit within the maximum allowed resolution of %resolution pixels', array('%resolution' => $resolution, '%filename' => $file['filename'])));
      }
    }
  }
  return $file;
}


/**
 * Implementation of hook_widget().
 */
function imagefield_widget(&$form, &$form_state, $field, $items) {
  return array(
    '#type' => $field['widget']['type'],
    '#title' => $field['widget']['label'],
    '#weight' => $field['widget']['weight'],
    '#default_value' => $items,
    '#required' => $field['required'],
    '#multiple' => $field['multiple'] == 0 ? FALSE : TRUE,
    '#multiple_limit' => $field['multiple'] == 1 ? 0 : $field['multiple'],
    '#element_validate' => array('_imagefield_widget_validate'),
    '#field' => $field,
  );
  
}

function _imagefield_widget_prepare_form_values(&$node, $field, &$items) {
  $fieldname = $field['field_name'];
  // clean up the session if we weren't posted.
  if (!count($_POST)) {
    imagefield_clear_session();
  }

  // Attach new files
  if ($file = file_check_upload($fieldname .'_upload')) {
    $file = (array)$file;

    // Validation must happen immediately after the image is uploaded so we
    // can discard the file if it turns out not to be a valid mime type
    $valid_image = _imagefield_widget_upload_validate($node, $field, $items, $file);
    //$valid_image = true;

    if ($valid_image) {
      $file = _imagefield_scale_image($file, $field['widget']['max_resolution']);

      global $user;
      $widget_image_path = token_replace($field['widget']['image_path'], 'user', $user);

      imagefield_check_directory($widget_image_path);
      $filepath = file_create_filename($file['filename'], file_create_path($widget_image_path));

      $file['fid'] = 'upload';
      $file['preview'] = $filepath;

      // If a single field, mark any other images for deletion and delete files in session
      if (!$field['multiple']) {
        if (is_array($items)) {
          foreach ($items as $delta => $session_file) {
            $items[$delta]['flags']['hidden'] = true;
            $items[$delta]['flags']['delete'] = true;
          }
        }
        imagefield_clear_field_session($fieldname);
      }
      // Add the file to the session
      $file_id = count($items) + count($_SESSION['imagefield'][$fieldname]);
      $file['sessionid'] = $file_id;
      $_SESSION['imagefield'][$fieldname][$file_id] = $file;
    }
    else {
      // Delete the invalid file
      file_delete($file['filepath']);

      // If a single field and a valid file is in the session, mark existing image for deletion
      if (!$field['multiple']) {
        if (!empty($_SESSION['imagefield'][$fieldname]) && !empty($items)) {
          foreach ($items as $delta => $session_file) {
            $items[$delta]['flags']['hidden'] = true;
            $items[$delta]['flags']['delete'] = true;
          }
        }
      }
    }
  }

  // Load files from preview state. before committing actions.
  if (is_array($_SESSION['imagefield'][$fieldname]) && count($_SESSION['imagefield'][$fieldname])) {
    foreach ($_SESSION['imagefield'][$fieldname] as $delta => $file) {
      $items[] = $file;
    }
  }
}

function _imagefield_widget_form($node, $field, &$items) {
  drupal_add_js('misc/progress.js');
  drupal_add_js('misc/upload.js');
  drupal_add_js(drupal_get_path('module', 'imagefield') .'/imagefield.js');
  drupal_add_css(drupal_get_path('module', 'imagefield') .'/imagefield.css');

  $fieldname = $field['field_name'];

  $form = array();

  $form[$fieldname] = array(
    '#type' => 'fieldset',
    '#title' => t($field['widget']['label']),
    '#weight' => $field['widget']['weight'],
    '#description' => t('Images are not saved until the form is submitted.'),
    '#collapsible' => true,
    '#collapsed' => false,
    '#tree' => true,
    '#prefix' => '<div id="'. form_clean_id($fieldname .'-attach-wrapper') .'">',
    '#suffix' => '</div>',
  );

  $form[$fieldname]['new'] = array(
    '#tree' => false,
    '#prefix' => '<div id="'. form_clean_id($fieldname .'-attach-hide') .'">',
    '#suffix' => '</div>',
    '#weight' => 100,
  );

  $max_images = $field['widget']['max_number_images'];
  if ($field['multiple'] && $max_images && $max_images <= count($items)) {
    $form[$fieldname]['#prefix'] = '<div>';
    $form[$fieldname]['new']['#prefix'] = '<div>';
    $form[$fieldname]['new']['#value'] = format_plural($max_images, 'You can only attach one image to this field. Delete the image if you wish to be able to upload a different one.', 'You can only attach @count images to this field. Delete an image if you wish to be able to upload different images.');
  }
  else {

    // multiupload: add an add new field button.
    // onchange ajax upload each file input after validation.
    // update date 'file_inputs' with qty of file inputs.
    // name file inputs $fieldname .'_upload_'. number of file input.
    // inprepare form_values hook iterate over each input.
    // can we display files sizes to predict the total size of an upload.

    $extensions_description = empty($field['widget']['file_extensions'])
    ? ''
    : t('<br />Allowed extensions: %ext', array('%ext' => $field['widget']['file_extensions']));

    // Seperate from tree becase of that silly things won't be
    // displayed if they are a child of '#type' = form issue
    $form[$fieldname]['new'][$fieldname .'_upload'] = array(
      '#type'  => 'file',
      '#title' => t('Upload a new image'),
      '#description' => $field['widget']['description'] . $extensions_description,
      '#tree' => false,
      '#weight' => 9,
      '#attributes' => array('class' => 'imagefield imagefield-'. $fieldname, 'accept' => str_replace(' ', '|', trim($field['widget']['file_extensions']))),
    );

    $form[$fieldname]['new']['upload'] = array(
      '#type' => 'button',
      '#value' => t('Upload'),
      '#name' => 'cck_imagefield_'. $fieldname .'_op',
      '#id' => form_clean_id($fieldname .'-attach-button'),
      '#tree' => false,
      '#weight' => 10,
    );
    // The class triggers the js upload behaviour.
    $form[$fieldname .'-attach-url'] = array('#type' => 'hidden', '#value' => url('imagefield/js', null, null, true), '#attributes' => array('class' => 'upload'));
  }

  // @todo split following if block into its own function.
  // Store the file data object to be carried on.
  if (!empty($items)) {
    foreach ($items as $delta => $file) {
      if ($file['filepath'] && !$file['flags']['hidden']) {
        $form[$fieldname][$delta] = array(
          '#theme' => 'imagefield_row',
        );

        $form[$fieldname][$delta]['flags']['delete'] = array(
          '#type' => 'checkbox',
          '#title' => t('Delete'),
          '#default_value' => isset($file['flags']['delete']) ? $file['flags']['delete'] : 0,
        );

        global $user;
        $filename = $file['fid'] == 'upload' ? file_create_filename($file['filename'], file_create_path(token_replace($field['widget']['image_path'], 'user', $user))) : $file['filepath'];

        $form[$fieldname][$delta]['admin_preview'] = array(
          '#type' => 'markup',
          '#value' => theme('imagefield_image', $file, $file['alt'], $file['title'], array('width' => '150'), false),
        );

        $form[$fieldname][$delta]['description'] = array(
          '#type' => 'markup',
          '#value' => '<strong>'. t('Filename: ') .'</strong>'. $file['filename'],
        );

        $form[$fieldname][$delta]['alt'] = array(
          '#type' => 'hidden',
          '#value' => $file['filename'],
        );
        // overwrite with an input field if custom_alt is flagged;
        if ($field['widget']['custom_alt']) {
          $form[$fieldname][$delta]['alt'] = array(
            '#type' => 'textfield',
            '#title' =>  t('Alternate text'),
            '#default_value' => $file['alt'],
            '#description' => t('Alternate text to be displayed if the image cannot be displayed.'),
            '#maxlength' => 255,
            '#size' => 10,
          );
        }

        $form[$fieldname][$delta]['title'] = array(
          '#type' => 'hidden',
          '#value' => $file['filename'],
        );
        // overwrite with an input field if custom_title is flagged;
        if ($field['widget']['custom_title']) {
          $form[$fieldname][$delta]['title'] = array(
            '#type' => 'textfield',
            '#title' =>  t('Title'),
            '#default_value' =>  $file['title'],
            '#description' => t('Text to be displayed on mouse overs.'),
            '#maxlength' => 255,
            '#size' => 10,
          );
        }

        // Special handling for single value fields
        if (!$field['multiple']) {
          $form[$fieldname][$delta]['replace'] = array(
            '#type' => 'markup',
            '#value' => t('If a new image is chosen, the current image will be replaced upon submitting the form.'),
          );
        }
      }
      elseif ($file['filepath'] && $file['flags']['hidden']) {
        // Render all the form values of this item if it is hidden.
        $form[$fieldname][$delta]['flags']['hidden'] = array('#type' => 'value', '#value' => $file['flags']['hidden']);
        $form[$fieldname][$delta]['flags']['delete'] = array('#type' => 'value', '#value' => $file['flags']['delete']);
        $form[$fieldname][$delta]['title'] = array('#type' => 'value', '#value' => $file['title']);
        $form[$fieldname][$delta]['alt'] = array('#type' => 'value', '#value' => $file['alt']);
      }
      if (isset($file['sessionid'])) {
        $form[$fieldname][$delta]['sessionid'] = array('#type' => 'value',  '#value' => $file['sessionid']);
      }
      $form[$fieldname][$delta]['filename'] = array('#type' => 'value',  '#value' => $file['filename']);
      $form[$fieldname][$delta]['filepath'] = array('#type' => 'value',  '#value' => $file['filepath']);
      $form[$fieldname][$delta]['preview'] = array('#type' => 'value',  '#value' => $file['preview']);
      $form[$fieldname][$delta]['filemime'] = array('#type' => 'value',  '#value' => $file['filemime']);
      $form[$fieldname][$delta]['filesize'] = array('#type' => 'value',  '#value' => $file['filesize']);
      $form[$fieldname][$delta]['fid'] = array('#type' => 'value',  '#value' => $file['fid']);
    }
  }

  // Some useful info for our js callback.
  $form['vid'] = array(
    '#type' => 'hidden',
    '#value' => $node->vid,
    '#tree' => false,
  );
  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => $node->nid,
    '#tree' => false,
  );
  $form['type'] = array(
    '#type' => 'hidden',
    '#value' => $node->type,
    '#tree' => false,
  );

  return $form;
}

/**
 * Validate the widget.
 */
function _imagefield_widget_validate($node, $field, $items) {

  if ($field['required']) {
    // Sum all the items marked for deletion, so we can make sure the end user
    // isn't deleting all of the images.
    $deleted = 0;
    foreach ($items as $item) {
      if ($item['flags']['delete']) {
        ++$deleted;
      }
    }

    if (!count($items)) {
      form_set_error($field['field_name'], t('@field is required. Please upload an image.', array('@field' => $field['widget']['label'])));
    }
    else if (count($items) == $deleted ) {
      form_set_error($field['field_name'],  t('@field is required. Please uncheck at least one delete checkbox or upload another image.', array('@field' => $field['widget']['label'])));
    }
  }
}

function _imagefield_widget_upload_validate($node, $field, $items, $file) {
  // initialize our validation state, innocent until proven guilty.
  $valid = true;

  // Do we even need to test file extensions?
  if (!empty($field['widget']['file_extensions'])) {
    // Pop out the extensions and turn file_extensions into an array.
    $ext = strtolower(array_pop(explode('.', $file['filename'])));
    $allowed_extensions = array_unique(explode(' ', strtolower(trim($field['widget']['file_extensions']))));
    // Is it the file extension in the allowed_extensions array?
    if (!in_array($ext, $allowed_extensions)) {
      // Sorry no..
      form_set_error($field['field_name'], t('Files with the extension %ext are not allowed. Please upload a file with an extension from the following list: %allowed_extensions', array('%ext' => $ext, '%allowed_extensions' => $field['widget']['file_extensions'])));
      $valid = false;
    }
  }

  // If max filesize is set.
  if (!empty($field['widget']['max_filesize'])) {
    if ($file['filesize'] > ($field['widget']['max_filesize'] * 1024)) {
      form_set_error($field['field_name'], t('The file you uploaded has a filesize greater than the maximum allowed filesize of %sizekb.', array('%size' => $field['widget']['max_filesize'])));
      $valid = false;
    }
  }

  // Is the mime type a match for image.
  if (strpos($file['filemime'], 'image/') !== 0) {
    // sorry no it isn't. do not pass go, do not collect $200.
    form_set_error($field['field_name'], t('Mime Type mismatch. Only image files may be upload. You uploaded a file with mime type: %mime', array('%mime' => $file['filemime'])));
    $valid = false;
  }

  // If max number of images is set
  if ($field['multiple'] && !empty($field['widget']['max_number_images'])) {
    $count = count($items) + count($_SESSION['imagefield'][$field['field_name']]);
    if ($count >= $field['widget']['max_number_images']) {
      form_set_error($field['field_name'], t('You are only allowed to upload up to %maximages images.', array('%maximages' => $field['widget']['max_number_images'])));
      $valid = false;
    }
  }

  return $valid;
}


/**
 * Implementation of hook_field_formatter_info().

 */
function imagefield_field_formatter_info() {
  $formatters = array(
    'image_plain' => array(
      'label' => t('Default'),
      'field types' => array('image'),
    ),
    'image_nodelink' => array(
      'label' => t('link to node'),
      'field types' => array('image'),
    ),
    'image_imagelink' => array(
      'label' => t('link to image'),
      'field types' => array('image'),
    ),
    'path_plain' => array(
       'label' => t('path to image'),
       'field types' => array('image'),
    ),   
    'url_plain' => array(
       'label' => t('url to image'),
       'field types' => array('image'),
    ),   
  );
  return $formatters;
}

function theme_imagefield_formatter_image_plain($element) {
  $field = $element['#field'];
  $item = $element['#item'];

  if (empty($item['fid']) && $field['use_default_image']) $item = $field['default_image'];
  if (empty($item['filepath']))  $item = array_merge($item, _imagefield_file_load($item['fid']));
  
  $class = 'imagefield imagefield-'. $field['field_name'];
  return  theme('imagefield_image', $item, $item['alt'], $item['title'], array('class' => $class));
}

function theme_imagefield_formatter_image_nodelink($element) {
  $field = $element['#field'];
  $node = $element['#node'];

  $imagetag = theme('imagefield_formatter_image_plain', $element);
  $class = 'imagefield imagefield-nodelink imagefield-'. $field['field_name'];
  return l($imagetag, 'node/'. $node->nid, array('class' => $class), null, null, false, true);
}

function theme_imagefield_formatter_image_imagelink($element) {
  $field = $element['#field'];
  $item = $element['#item'];

  $imagetag = theme('imagefield_formatter_image_plain', $element);
  $original_image_url = file_create_url($item['filepath']);
  $class = 'imagefield imagefield-imagelink imagefield-'. $field['field_name'];
  return l($imagetag, $original_image_url, array('class' => $class), null, null, false, true);
}

function theme_imagefield_formatter_path_plain($element) {
  $field = $element['#field'];
  $item = $element['#item'];
  if (empty($item['fid']) && $field['use_default_image'])  $item = $field['default_image'];
  // If there is no image on the database, use default.
  if (empty($item['filepath']))  $item = array_merge($item, _imagefield_file_load($item['fid']));

  $attributes['class'] .= ' imagefield-formatter-path';
  return '<span '. drupal_attributes($attributes) .'>'. file_create_path($item['filepath']) .'</span>';
}

function theme_imagefield_formatter_url_plain($element) {
  $field = $element['#field'];
  $item = $element['#item'];
  if (empty($item['fid']) && $field['use_default_image'])  $item = $field['default_image'];
  // If there is no image on the database, use default.
  if (empty($item['filepath']))  $item = array_merge($item, _imagefield_file_load($item['fid']));

  $attributes['class'] .= ' imagefield-formatter-url';
  return '<span '. drupal_attributes($attributes) .'>'. file_create_url($item['filepath']) .'</span>';
}


function theme_imagefield_row($element) {
  $output = '<div class="imagefield-edit-preview">'. drupal_render($element['admin_preview']) .'</div>';
  $output .= '<div class="imagefield-edit-image-detail">';
  $output .= '<div class="imagefield-edit-image-flags">'. drupal_render($element['flags']) .'</div>';
  $output .= '<div class="imagefield-edit-image-description">'. drupal_render($element['description']);
  $output .= '</div>';
  $output .= drupal_render($element['alt']);
  $output .= drupal_render($element['title']);
  $output .= drupal_render($element['fid']);
  $output .= '</div>';
  if (isset($element['replace'])) {
    $output .= '<div class="imagefield-edit-image-replace">'. drupal_render($element['replace']) .'</div>';
  }
  return $output;
}

/**
 * FormAPI theme function. Theme the output of an image field.
 */
function theme_imagefield_widget_default(&$element) {
  $output = '';

  // Always add tabledrag in case a table is created after uploads.
  if ($element['#multiple']) {
    drupal_add_tabledrag($element['#id'] .'-table', 'order', 'sibling', $element['#id'] .'-weight');
  }

  // Print out the existing images.
  if ($element['#multiple'] && !empty($element['#files'])) {
    $rows = array();
    foreach ($element['#files'] as $fid => $file) {
      $element[$fid]['weight']['#attributes']['class'] = isset($element[$fid]['weight']['#attributes']['class']) ? ($element[$fid]['weight']['#attributes']['class'] .' '. $element['#id'] .'-weight') : $element['#id'] .'-weight';

      $row = array();
      $row[] = array('data' => '', 'class' => 'content-multiple-drag');
      $row[] = theme('imagefield_row', $element[$fid]);
      $row[] = drupal_render($element[$fid]['weight']);
      $rows[] = array('data' => $row, 'class' => 'draggable');
    }

    $existing_items = theme('table', array(), $rows, array('id' => $element['#id'] .'-table'));
  }
  elseif (!empty($element['#files'])) {
    foreach ($element['#files'] as $file) {
      if ($file['fid'] && empty($file['flags']['hidden'])) {
        $existing_items = '<div class="clear-block">'. theme('imagefield_row', $element[$file['fid']]) .'</div>';
        break;
      }
    }
  }

  if (isset($existing_items)) {
    $existing_element = array(
      '#type' => 'element',
      '#title' => $element['#title'],
      '#required' => $element['#image_required'],
    );
    $output .= theme('form_element', $existing_element, $existing_items);
    unset($element['new'][$element['#field']['field_name'] .'_upload']['#title']);
  }
  else {
    $element['new'][$element['#field']['field_name'] .'_upload']['#required'] = $element['#image_required'];
  }

  // Additional image information and upload controls.
  if (isset($element['replace'])) {
    $output .= '<div class="imagefield-edit-image-replace">'. drupal_render($element['replace']) .'</div>';
  }
  $output .= drupal_render($element['new']);
  $output = '<div id="'. $element['#id'] .'-wrapper" class="imagefield-element clear-block">'. $output .'</div>';

  return $output;
}



function theme_imagefield_image($file, $alt = '', $title = '', $attributes = null, $getsize = true) {
  $file = (array)$file;
  if (!is_file($file['filepath'])) {
    return;
  }
  $image_attributes = array();
  if (!$getsize || (list($width, $height, $type, $image_attributes) = @getimagesize($file['filepath']))) {
    $attributes = drupal_attributes($attributes);
    $alt = empty($alt) ? $file['alt'] : $alt;
    $title = empty($title) ? $file['title'] : $title;
    $url = file_create_url($file['filepath']);
    return '<img src="'. check_url($url) .'" alt="'.
        check_plain($alt) .'" title="'. check_plain($title) .'" '. $image_attributes . $attributes .' />';
  }
}

/**
 * Implementation of hook_file_download().
 * Replicated from upload.module.
 *
 * Conditionally included since we're just replicating the
 * work of upload.module for now.
 */

if (!function_exists('upload_file_download')) {
  function imagefield_file_download($file) {
    // if this isn't a default image look it up from the db...
    if (strpos($file, 'imagefield_default_images') !== false) {
      $fieldname = array_shift(explode('.', basename($file)));
      $field = content_fields($fieldname);
      $file = $field['default_image'];
    }
    else {
      $file = file_create_path($file);

      $result = db_query("SELECT f.* FROM {files} f WHERE filepath = '%s'", $file);
      if (!$file = db_fetch_object($result)) {
        // We don't really care about this file.
        return;
      }
    }

    // @todo: check the node for this file to be referenced in a field
    // to determine if it is managed by imagefield. and do the access denied part here.
    if (!user_access('view imagefield uploads')) {
      // sorry you do not have the proper permissions to view
      // imagefield uploads.
      return -1;
    }

    // @hack: default images dont' have nids....
    // I'm not going to bother checking perms for default images...
    // it's a bug, but we'll resolve it later.
    if (!empty($file->nid)) {
      $node = node_load($file->nid);
      if (!node_access('view', $node)) {
        // You don't have permission to view the node
        // this file is attached to.
        return -1;
      }
    }

    // Well I guess you can see this file.
    $name = mime_header_encode($file->filename);
    $type = mime_header_encode($file->filemime);
    // Serve images and text inline for the browser to display rather than download.
    $disposition = ereg('^(text/|image/)', $file->filemime) ? 'inline' : 'attachment';
    return array(
      'Content-Type: '. $type .'; name='. $name,
      'Content-Length: '. $file->filesize,
      'Content-Disposition: '. $disposition .'; filename='. $name,
      'Cache-Control: private',
    );
  }
}

/**
 * Menu-callback for JavaScript-based uploads.
 */
function imagefield_js($node_type, $fieldname) {
  $field = content_fields($fieldname, $node_typ);

  $form_state = array('values' => $_POST);
  $form_state['values'][$fieldname] = isset($form_state['values'][$fieldname]) ? $form_state['values'][$fieldname] : array();

  // Load in the form cache.
  $form = form_get_cache($_POST['form_build_id'], $form_state);
   
  // Find field group if needed and assign the form element by reference.
  // @hack: Well duh I can see what you're doing, but why are you doing it? -dopry
  if (function_exists('fieldgroup_get_group') && $group = fieldgroup_get_group($node_type, $fieldname)) {
    $form_element =& $form[$group][$fieldname];
  }
  else {
    $form_element =& $form[$fieldname];
  }

  // Handle new uploads.
  _imagefield_widget_validate($form_element, $form_state);

  // Add the new element to the stored form and form_state then resave.
  $form_element = imagefield_widget($form, $form_state, $field, $form_state['values'][$fieldname]);
  $form_state['storage'][$fieldname] = $form_state['values'][$fieldname];
  form_set_cache($_POST['form_build_id'], $form, $form_state);


  // Render the form for output.
  $form['#post'] = $_POST;
  $form['#programmed'] = TRUE;
  $form_state['submitted'] = FALSE;

  drupal_alter('form', $form, $form_state, 'imagefield_js');
  $form = form_builder('imagefield_js', $form, $form_state);
 
  $output = theme('status_messages') . drupal_render($form_element);

  // We send the updated file attachments form.
  drupal_set_header('Content-Type: application/json; charset=utf-8');
  print drupal_to_js(array('status' => true, 'data' => $output));
  exit;

}
