<?php
// $Id$

function json_server_server_info() {
  return array(
    '#name' => 'JSON',
    '#path' => 'json'
  );
}

function json_server_server() {
  $methods = services_get_all();
  $request = drupal_parse_json($_POST['method']);
  $args = array();
  foreach($methods as $method) {
    if($method['#method'] == $request) {
      unset($_POST['q']);
      unset($_POST['method']);
      $args = array();
      foreach($method['#args'] as $arg) {
        if(isset($_POST[$arg['#name']])) {
          $args[] = drupal_parse_json($_POST[$arg['#name']]);
        }
        elseif($arg['#optional'] == 0) {
          return drupal_to_js(array("#error" => TRUE, "#data" => "Argument ". $arg['#name'] ." not recieved"));
        }
        else {
          $args[$arg['#name']] = '';
        }
      }
      print_r($args);
      return drupal_to_js(array('#error' => FALSE, '#data' => services_method_call($method['#method'], $args)));
    }
  }
  return "error";
}

function json_load() {
  global $base_url;
  $path = drupal_get_path("module", "json_server");
  drupal_add_js($path ."/jquery.json.js");
  drupal_add_js(array("baseurl" => $base_url ."/"), 'setting');
}

function drupal_parse_json($v) {
  if($v{0} == '"') {
    $v = substr($v, 1, -1);
  }
  elseif($v{0} == '{') {
    $var = explode(",", substr($v, 1, -2));
    $v = array();
    foreach($var as $value) {
      $va = explode(":", $value);
      $v[] = drupal_parse_json($va[1]);
    }
  }
  return $v;
}