<?php
// $Id$

function json_server_server_info() {
  return array(
    '#name' => 'JSON',
    '#path' => 'json',
  );
}

function json_server_server_error($message) {
  return array("status" => FALSE, "message" => $message);
}

function json_server_server() {
  if (!isset($_POST)) {
    return "JSON server accepts POST requests only.";
  }
  
  $request = $_POST['method'];
  $methods = services_get_all();
  $args = array();
  foreach ($methods as $method) {
    if ($method['#method'] == $request) {
      unset($_POST['q']);
      unset($_POST['method']);
      $args = array();
      foreach($method['#args'] as $arg) {
        if(isset($_POST[$arg['#name']])) {
          $args[] = $_POST[$arg['#name']];
        }
        elseif($arg['#optional'] == 0) {
          return drupal_to_js(array("status" => FALSE, "data" => "Argument ". $arg['#name'] ." not recieved"));
        }
        else {
          $args[$arg['#name']] = NULL;
        }
      }
      $result = services_method_call($method['#method'], $args);
      if (is_array($result) && isset($result['#error']) && $result['#error'] === TRUE)
        return drupal_to_js(array('status' => FALSE, 'data' => $result['#message']));
      
      return drupal_to_js(array('status' => TRUE, 'data' => $result));
    }
  }

  return drupal_to_js(array('status' => FALSE, 'data' => "Invalid method $request"));
}

function json_load() {
  global $base_url;
  $path = drupal_get_path("module", "json_server");
  drupal_add_js($path ."/json_server.js");
}