<?php
// $Id$

/**
 * @file
 * Definition of the 'tabs' panel style.
 */

//----------------------------------------------------------------------------
// Panels hooks.

/**
 * Implementation of hook_panels_styles().
 */
function panels_tabs_panels_styles() {
  return array(
    'tabs' => array(
      'title'             => t('Tabs'),
      'description'       => t('Presents the panes in tabs.'),
      'render panel'      => 'panels_tabs_style_render_panel',
      'settings form'     => 'panels_tabs_style_settings_form',
      'settings validate' => 'panels_tabs_style_settings_validate',
    ),
  );
}


//----------------------------------------------------------------------------
// Panels style plugin callbacks.

/**
 * Render callback.
 */
function theme_panels_tabs_style_render_panel($display, $panel_id, $panes, $settings) {
  $output = '';

  $tabs = array();
  $id = $display->css_id .'-'. $panel_id;

  // Add the Javascript to the page, and save the settings for this panel.
  panels_tabs_add_js();
  drupal_add_js(
    array(
      'panelsTabs' => array(
        $display->css_id => array(
          'fillingTabs' => $settings['filling_tabs'],
        ),
      )
    ),
    'setting'
  );

  $tabs[$id] = array(
    '#type' => 'tabset',
  );
  foreach ($panes as $pane_id => $content) {
    // Remove the title from the content. We don't want titles in both the tab
    // and the content associated with the tab.
    $content_without_title = drupal_clone($content);
    unset($content_without_title->title);

    $tabs[$id][$pane_id] = array(
      '#type' => 'tabpage',
      '#title' => $content->title,
      '#content' => theme('panels_pane', $content_without_title, $display->content[$pane_id], $display),
      '#weight' => $pane_id,
    );
  }
  $output = tabs_render($tabs);
  
  return $output;
}

/**
 * Settings form callback.
 */
function panels_tabs_style_settings_form($style_settings) {
  $form['filling_tabs'] = array(
    '#type' => 'radios',
    '#title' => t('Horizontally filling tabs'),
    '#options' => array(
      'disabled' => t('Disabled'),
      'equal' => t('Equal width tabs'),
      'smart' => t('Equal width scaling tabs'),
    ),
    '#description' => t(
      "Horizontally filling tabs make sure the tabs consume all available
      horizontal space.<br />
      Equal width tabs: sets the <em>width</em> property, forcing each tab
      to be equally wide. If the text doesn't fit in the tab, the overflow
      will be hidden.<br />
      Horizontally filling, smart width tabs: calculates the length of the
      text in each tab and compares this to the total length of the text on
      all tabs. It then sets the width property of each tab according to the
      percentage of text the tab contains."
    ),
    '#default_value' => (isset($style_settings['filling_tabs'])) ? $style_settings['filling_tabs'] : 'disabled',
  );
  return $form;
}

/**
 * Settings form validation callback.
 */
function panels_tabs_style_settings_validate($style_settings, $form, $form_values) {
  if (!in_array($form_values['filling_tabs'], array('disabled', 'equal', 'smart'))) {
    form_error($form['filling_tabs'], t('Invalid value detected.'));
  }
}


//----------------------------------------------------------------------------
// Private functions.

/**
 * Adds the .js file only once per page load.
 */
function panels_tabs_add_js() {
  static $added = FALSE;

  if (!$added) {
    drupal_add_js(drupal_get_path('module', 'panels_tabs') .'/panels_tabs.js');
    $added = TRUE;
  }
}
