<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function robotstxt_help($path, $arg) {
  switch ($path) {
    case 'admin/help#robotstxt':
      return '<p>'. t('In a multisite environment, there is no mechanism for having a separate robots.txt file for each site. This module addresses that need by letting you administer the robots.txt file from the settings interface.') .'</p>';
      break;
    case 'admin/settings/robotstxt':
      if (file_exists('./robots.txt')) {
        drupal_set_message(t('One or more problems have been detected with the RobotsTxt configuration. Check the <a href="@status">status report</a> for more information.', array('@status' => url('admin/reports/status'))), 'warning');
      }
      return t('See <a href="http://www.robotstxt.org/">http://www.robotstxt.org/</a> for more information concerning how to write your <a href="@robotstxt">robots.txt</a> file.', array('@robotstxt' => base_path() . 'robots.txt'));
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function robotstxt_menu() {
  $items['robots.txt'] = array(
    'page callback' => 'robotstxt_robots',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/robotstxt'] = array(
    'title' => 'RobotsTxt',
    'description' => 'Manage your robots.txt file.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('robotstxt_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'robotstxt.admin.inc',
  );

  return $items;
}

/**
 * Serve up the robots.txt file stored in the db.
 */
function robotstxt_robots() {
  $base = variable_get('robotstxt', FALSE);

  if ($base === FALSE) {
    $base = _robotstxt_get_file_contents();
  }

  drupal_set_header("Content-type: text/plain");
  echo trim(check_plain($base));

  // Hook other modules for adding additional lines to robots.txt
  $lines = module_invoke_all('robotstxt');
  foreach ($lines as $line) {
    $line = check_plain($line);
    if ($line != '') {
      echo "\n" . trim($line);
    }
  }

  exit;
}

/**
 * Retrieve contents of robots.txt from site root or module directory
 */
function _robotstxt_get_file_contents() {
  $file_contents = '';

  if (file_exists('./robots.txt')) {
    $file_contents = check_plain(file_get_contents('./robots.txt'));
  }
  elseif (file_exists(drupal_get_path('module', 'robotstxt') .'/robots.txt')) {
    $file_contents = check_plain(file_get_contents(drupal_get_path('module', 'robotstxt') .'/robots.txt'));
  }

  return $file_contents;
}
