<?php
// $Id$

/**
 * @file
 * Installation and update proceedures for the search_attachments module.
 */

function search_attachments_uninstall() {
  db_query('DELETE FROM {search_dataset} WHERE TYPE LIKE "attachment"');
  db_query('DELETE FROM {search_index} WHERE TYPE LIKE "attachment"');
  db_query('DELETE FROM {variable} WHERE name LIKE "search_attachments_%"');
  drupal_set_message(t('Search Attachments successfully uninstalled.'));
}