<?php
// $Id$

/**
 * @file
 * SEO Checklist module allows users to track important SEO techniques on the website.
 */

/**
 * Implementation of hook_help().
 */
function seochecklist_help($path, $arg) {
  if ($path == 'admin/settings/seochecklist') {
    return '<p><strong>' . t("Check off each SEO-related task as you complete it. Do not forget to click <em>Save</em>!") . '</strong></p>';
  }
}

/**
 * Implementation of hook_perm().
 */
function seochecklist_perm() {
  return array('access seochecklist content');
}

/**
 * Implementation of hook_menu().
 */
function seochecklist_menu() {
  $items['admin/settings/seochecklist'] = array(
    'title' => 'SEO Checklist',
    'description' => t('Keep track of your Drupal Search Engine Optimization tasks.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('seochecklist_admin_settings'),
    'access arguments' => array('access seochecklist content'),
    'file' => 'seochecklist.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_footer().
 */
function seochecklist_footer($main = 0) {
  if (variable_get('seo_checklist_link', 0)) {
    return '<div align="center"><a href="http://www.volacci.com/" target="_blank">Drupal SEO</a></div>';
  }
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 *
 * Add vertical tabs to the checklist page.
 */
function seochecklist_form_seochecklist_admin_settings_alter(&$form, $form_state) {
  if (module_exists('vertical_tabs') && function_exists('vertical_tabs_add_vertical_tabs')) {
    vertical_tabs_add_vertical_tabs($form);
    $form['save_above']['#attributes']['class'] = 'js-hide';
  }
  else {
    drupal_set_message(t('Your SEO Checklist interface will be greatly enhanced by installing the <a href="@vertical-tabs">Vertical Tabs module</a>.', array('@vertical-tabs' => 'http://drupal.org/project/vertical_tabs')), 'status', FALSE);
  }
}
