<?php
// $Id$

/**
 * @file
 * Notifies administrator of new user registrations.
 */


/**
 * Implementation of hook_menu().
 */
function user_register_notify_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/settings/register_notify',
      'title' => t('User Register Notify'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('user_register_notify_settings'),
      'description' => t('Configure the User Register Notify module.'),
      'access' => user_access('administer site configuration')
    );
  }
  return $items;
}


/**
 * Menu callback for admin settings form.
 */
function user_register_notify_settings() {
  $form['user_register_notify_mailto'] = array(
    '#type' => 'textfield',
    '#title' => t('Send notifications to this email address'),
    '#description' => t('If you leave this blank, the site email address, %mailto, will be used.', array('%mailto' => variable_get('site_mail', ini_get('sendmail_from')))),
    '#default_value' => variable_get('user_register_notify_mailto', ''),
  );
  return system_settings_form($form);
}


/**
 * Implementation of hook_user().
 */
function user_register_notify_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'insert':
      // Notify administrator of new user only if this is not first user and
      // if visitors can create accounts without administrator's approval.
      // In case when accounts must be created with administrator's approval
      // there is already a 'pending approval' e-mail notification.
      if ($account->uid != 1 && $account->status) {
        $subject = t('Account details for !username at !site', array('!username' => $account->name, '!site' => variable_get('site_name', 'Drupal')));
        if (variable_get('user_register_notify_mailto', FALSE) != FALSE) {
          $to = $from = variable_get('user_register_notify_mailto', 'site_mail');
        }
        else {
          $to = $from = variable_get('site_mail', ini_get('sendmail_from'));
        }

        drupal_mail(
          'user-register-notify-admin',
          $to,
          $subject,
          t("!user (!uri) has created account.\n\n!edit-uri", array('!uri' => url("user/$account->uid", NULL, NULL, TRUE), '!user' => $account->name, '!edit-uri' => url("user/$account->uid/edit", NULL, NULL, TRUE))),
          $from
        );
      }
      break;
  }
}
