<?php
// $Id$
// Built for Drupal 6

/**
 * @file
 * Notifies administrator of new user registrations.
 */

/**
 * Implementation of hook_help().
 */
function user_register_notify_help($path, $arg) {
  if ($path == 'admin/help#user_register_notify') {
    return '<p>'.
      t('This module provides a way for an administrator to get'.
      'an email when a user account is created. '.
      'It assumes that the Drupal mailer is configured.') .
      '</p>';
  }
}

define('USER_REGISTER_NOTIFY_SUBJECT', t('Account details for !user_name at !site'));
define('USER_REGISTER_NOTIFY_BODY', t("!user_name (!user_view) has created account.\n\nEdit user: !user_edit\n\nDelete User: !user_delete\n\n!profile"));

/**
 * Implementation of hook_menu().
 */
function user_register_notify_menu() {
  $items['admin/settings/register_notify'] = array(
    'title' => 'User Register Notify',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_register_notify_settings'),
    'description' => 'Configure the User Register Notify module.',
    'file' => 'user_register_notify.admin.inc',
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function user_register_notify_mail($key, &$message, $params) {

  if ($key == 'user-register-notify-admin') {
    $language = $message['language'];
    $langcode = $language->language;
    $uaccount = $params['account'];
    $account_data = "";
    if (module_exists('profile')) {
      $result = db_query('SELECT f.name, f.type, v.value FROM {profile_fields} f INNER JOIN {profile_values} v ON f.fid = v.fid WHERE uid = %d', $uaccount->uid);
      while ($field = db_fetch_object($result)) {
        switch ($field->type) {
          case 'date':
            $date_field = unserialize($field->value);
            if (is_array($date_field)) {
              $date_timestamp = mktime(0, 0, 0, $date_field['month'], $date_field['day'], $date_field['year']);
              $account_data .= sprintf("%s: %s\n", $field->name, format_date($date_timestamp));
            }
            break;
          case 'checkbox':
            if ($field->value)
              $account_data .= sprintf("%s: Checked\n", $field->name);
            else
              $account_data .= sprintf("%s: Not Checked\n", $field->name);
            break;
          default:
            $account_data .= sprintf("%s: %s\n", $field->name, $field->value);
        }
      }
    }
    $variables = array(
      '!user_name' => $uaccount->name,
      '!user_mail' => $uaccount->mail,
      '!user_view' => url('user/'. $uaccount->uid, array('absolute' => TRUE)),
      '!user_edit' => url('user/'. $uaccount->uid .'/edit', array('absolute' => TRUE)),
      '!user_delete' => url('user/'. $uaccount->uid .'/delete', array('absolute' => TRUE)),
      '!site' => variable_get('site_name', 'Drupal'),
      '!uri' => $base_url,
      '!uri_brief' => drupal_substr($base_url, drupal_strlen('http://')),
      '!date' => format_date(time()),
      '!profile' => check_plain($account_data),
    );
    $message['subject'] = t(variable_get('user_register_notify_subject', USER_REGISTER_NOTIFY_SUBJECT), $variables);
    $message['body'] = t(variable_get('user_register_notify_body', USER_REGISTER_NOTIFY_BODY), $variables);
  }
}

