<?php
// $Id$
/**
 * @author Services Dev Team
 * @file
 *  Link general file functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function file_service_perm() {
  return array('get binary files');
}

/**
 * Implementation of hook_service().
 */
function file_service_service() {
  return array(
    array(
      '#method'   => 'file.getFiles',
      '#callback' => 'file_service_get_files',
      '#access callback' => 'file_service_get_files_access',
      '#args'     => array(
        array(
          '#name'         => 'nid',
          '#type'         => 'int',
          '#description'  => t('A node id.'),
        ),
      ),
      '#return'   => 'array',
      '#help'     => t('Returns the files attached to a node.')
    ),
  );
}
