<?php

//$Id$

// Copyright 2005 Khalid Baheyeldin http://2bits.com

function currency_api_help($section) {
  switch ($section) {
    case 'admin/help#currency_api':
      return t('This module provides an API for currency conversion.');
  }
}

function currency_api_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path'               => 'admin/settings/currency_api',
      'title'              => t('Currency API'),
      'description'        => t('This module provides an API for currency exchange rates.'),
      'callback'           => 'drupal_get_form',
      'callback arguments' => array('currency_api_admin_settings'),
      'access'             => user_access('administer site configuration'),
      'type'               => MENU_SUGGESTED_ITEM, // optional
    );
  }
  return $items;
}
  
function currency_api_admin_settings() {    
  $form['currency_api_watchdog'] = array(
    '#type' => 'checkbox',
    '#title' => t('Log all currency exchange requests and errors to watchdog'),    
    '#default_value' => variable_get('currency_api_watchdog', 1),    
  );

  return system_settings_form($form);
}  

/**
 * Currency exchange rate API function
 *
 * This function converts two currencies using exchange rates from Yahoo Finance.
 * The currency codes are standard ISO 3-letter codes, and you can find the details
 * here:
 *  http://www.oanda.com/site/help/iso_code.shtml
 *
 * Here is an example on how to use it:
 *
 *   $from = 'CAD';
 *   $to   = 'USD';
 *   $amt  = 20;
 *   $ret = currency_exchange($from, $to, $amt);
 *   if ($ret['status'] == FALSE)
 *   {
 *     drupal_set_message(t('An error occured: '). $ret['message']);
 *   }
 *   else
 *   {
 *     print $amt .' '. $from .' = '. $ret['value'];
 *   }
 *
 * @param $currency_from
 *   Currency to convert from
 *
 * @param $currency_to
 *   Currency to convert to
 *
 * @param $amount
 *   Option amount to convert. If not supplied, 1 is assumed.
 *
 * @return $result
 *   An associative array that contains the following:
 *    $result['status'] TRUE or FALSE
 *    $result['message']'success' when status is TRUE, otherwise, contains a 
 *                      descriptive error text
 *   The following items are only returned when status is TRUE
 *    $result['value']  $amount * exchange rate of $currency_from into $currency_to
 *    $result['date']   Date of the last update to the rates (Format is "m/d/yyyy")
 *    $result['time']   Time of the last update to the rates (Format is "h:mmpm")
 */
function currency_api_convert($currency_from, $currency_to, $amount = 1) {
  $currency_array = array(
    's'  => 'Currencies',
    'l1' => 'Last',
    'd1' => 'Date',
    't1' => 'Time'
  );

  $result = array();
  $result['status']  = FALSE;
  $result['message'] = NULL;
  $result['value']   = 0;
  $result['date']    = NULL;
  $result['time']    = NULL;

  $from = strtoupper($currency_from);
  $to   = strtoupper($currency_to);

  $url = 'http://finance.yahoo.com/d/quotes.csv?e=.csv&f='. currency_api_get_fields($currency_array) .'&s='. $from . $to .'=X';

  // Validate the passed currency codes, to make sure they are valid
  if (FALSE == currency_api_get_desc($from)) {
    $msg = "currency: Invalid currency_from=$from";
    _log_to_watchdog($msg, WATCHDOG_ERROR);
    $result['message'] = $msg;
    $result['status'] = FALSE;
  }

  if (FALSE == currency_api_get_desc($to)) {
    $msg = "currency: Invalid currency_to=$to";
    _log_to_watchdog($msg, WATCHDOG_ERROR);
    return FALSE;
    $result['message'] = $msg;
    $result['status'] = FALSE;
  }

  if (!is_numeric($amount)) {
    $msg = "currency: Invalid amount=$amount";
    _log_to_watchdog($msg, WATCHDOG_ERROR);
    $result['message'] = $msg;
    $result['status'] = FALSE;
  }

  
  $record = file_get_contents($url);
  if ($record) {
    $currency_data = explode(',', $record);
    $rate = $currency_data[1];
    $date = $currency_data[2];
    $time = $currency_data[3];

    // Calculate the result
    $value = $amount * $rate;

    // Log it
    _log_to_watchdog("currency: $amount $from = $value $to", WATCHDOG_NOTICE);

    // Got what we need
    $result['value']  = $value;
    $result['date']   = $date;
    $result['time']   = $time;
    $result['status'] = TRUE;
    $result['message']= 'success';
  }
  else {
    $msg = 'currency: cannot contact Yahoo Finance host';
    _log_to_watchdog($msg, WATCHDOG_ERROR);
    $result['status'] = FALSE;
    $result['message'] = $msg;
  }

  return $result;
}


/**
 * Currency exchange API function
 *
 * This function gets the currency name for a standard ISO 3-letter codes,
 * You can find the details here:
 *  http://www.oanda.com/site/help/iso_code.shtml
 *
 * Here is an example on how to use it:
 *
 *   $ccode = 'CAD';
 *   $ret = currency_get_description($ccode);
 *   if ($ret == FALSE)
 *   {
 *     drupal_set_message(t('Could not get description'));
 *   }
 *   else
 *   {
 *     print $ccode .' => '. $ret;
 *   }
 *
 * @param $currency
 *   Currency code (3-letter ISO)
 *
 * @return $result
 *   Contains FALSE if the currency cannot be found, otherwise, it
 *   has the description.
 */
function currency_api_get_desc($currency) {
  foreach (currency_api_get_list() as $key => $description) {
    if ($key == $currency) {
      return $description;
    }
  }
  
  return FALSE;
}

function currency_api_get_list() {
  $currency = array(
    'AFA' => t('Afghanistan Afghani (AFA)'),
    'ALL' => t('Albanian Lek (ALL)'),
    'DZD' => t('Algerian Dinar (DZD)'),
    'ARS' => t('Argentine Peso (ARS)'),
    'AWG' => t('Aruba Florin (AWG)'),
    'AUD' => t('Australian Dollar (AUD)'),
    'BSD' => t('Bahamian Dollar (BSD)'),
    'BHD' => t('Bahraini Dinar (BHD)'),
    'BDT' => t('Bangladesh Taka (BDT)'),
    'BBD' => t('Barbados Dollar (BBD)'),
    'BYR' => t('Belarus Ruble (BYR)'),
    'BZD' => t('Belize Dollar (BZD)'),
    'BMD' => t('Bermuda Dollar (BMD)'),
    'BTN' => t('Bhutan Ngultrum (BTN)'),
    'BOB' => t('Bolivian Boliviano (BOB)'),
    'BWP' => t('Botswana Pula (BWP)'),
    'BRL' => t('Brazilian Real (BRL)'),
    'GBP' => t('British Pound (GBP)'),
    'BND' => t('Brunei Dollar (BND)'),
    'BGN' => t('Bulgarian Lev (BGN)'),
    'BIF' => t('Burundi Franc (BIF)'),
    'KHR' => t('Cambodia Riel (KHR)'),
    'CAD' => t('Canadian Dollar (CAD)'),
    'CVE' => t('Cape Verde Escudo (CVE)'),
    'KYD' => t('Cayman Islands Dollar (KYD)'),
    'XOF' => t('CFA Franc (BCEAO) (XOF)'),
    'XAF' => t('CFA Franc (BEAC) (XAF)'),
    'CLP' => t('Chilean Peso (CLP)'),
    'CNY' => t('Chinese Yuan (CNY)'),
    'COP' => t('Colombian Peso (COP)'),
    'KMF' => t('Comoros Franc (KMF)'),
    'CRC' => t('Costa Rica Colon (CRC)'),
    'HRK' => t('Croatian Kuna (HRK)'),
    'CUP' => t('Cuban Peso (CUP)'),
    'CYP' => t('Cyprus Pound (CYP)'),
    'CZK' => t('Czech Koruna (CZK)'),
    'DKK' => t('Danish Krone (DKK)'),
    'DJF' => t('Dijibouti Franc (DJF)'),
    'DOP' => t('Dominican Peso (DOP)'),
    'XCD' => t('East Caribbean Dollar (XCD)'),
    'ECS' => t('Ecuador Sucre (ECS)'),
    'EGP' => t('Egyptian Pound (EGP)'),
    'SVC' => t('El Salvador Colon (SVC)'),
    'ERN' => t('Eritrea Nakfa (ERN)'),
    'EEK' => t('Estonian Kroon (EEK)'),
    'ETB' => t('Ethiopian Birr (ETB)'),
    'EUR' => t('Euro (EUR)'),
    'FKP' => t('Falkland Islands Pound (FKP)'),
    'FJD' => t('Fiji Dollar (FJD)'),
    'GMD' => t('Gambian Dalasi (GMD)'),
    'GHC' => t('Ghanian Cedi (GHC)'),
    'GIP' => t('Gibraltar Pound (GIP)'),
    'XAU' => t('Gold Ounces (XAU)'),
    'GTQ' => t('Guatemala Quetzal (GTQ)'),
    'GNF' => t('Guinea Franc (GNF)'),
    'GYD' => t('Guyana Dollar (GYD)'),
    'HTG' => t('Haiti Gourde (HTG)'),
    'HNL' => t('Honduras Lempira (HNL)'),
    'HKD' => t('Hong Kong Dollar (HKD)'),
    'HUF' => t('Hungarian Forint (HUF)'),
    'ISK' => t('Iceland Krona (ISK)'),
    'INR' => t('Indian Rupee (INR)'),
    'IDR' => t('Indonesian Rupiah (IDR)'),
    'IRR' => t('Iran Rial (IRR)'),
    'IQD' => t('Iraqi Dinar (IQD)'),
    'ILS' => t('Israeli Shekel (ILS)'),
    'JMD' => t('Jamaican Dollar (JMD)'),
    'JPY' => t('Japanese Yen (JPY)'),
    'JOD' => t('Jordanian Dinar (JOD)'),
    'KZT' => t('Kazakhstan Tenge (KZT)'),
    'KES' => t('Kenyan Shilling (KES)'),
    'KRW' => t('Korean Won (KRW)'),
    'KWD' => t('Kuwaiti Dinar (KWD)'),
    'LAK' => t('Lao Kip (LAK)'),
    'LVL' => t('Latvian Lat (LVL)'),
    'LBP' => t('Lebanese Pound (LBP)'),
    'LSL' => t('Lesotho Loti (LSL)'),
    'LRD' => t('Liberian Dollar (LRD)'),
    'LYD' => t('Libyan Dinar (LYD)'),
    'LTL' => t('Lithuanian Lita (LTL)'),
    'MOP' => t('Macau Pataca (MOP)'),
    'MKD' => t('Macedonian Denar (MKD)'),
    'MGF' => t('Malagasy Franc (MGF)'),
    'MWK' => t('Malawi Kwacha (MWK)'),
    'MYR' => t('Malaysian Ringgit (MYR)'),
    'MVR' => t('Maldives Rufiyaa (MVR)'),
    'MTL' => t('Maltese Lira (MTL)'),
    'MRO' => t('Mauritania Ougulya (MRO)'),
    'MUR' => t('Mauritius Rupee (MUR)'),
    'MXN' => t('Mexican Peso (MXN)'),
    'MDL' => t('Moldovan Leu (MDL)'),
    'MNT' => t('Mongolian Tugrik (MNT)'),
    'MAD' => t('Moroccan Dirham (MAD)'),
    'MZM' => t('Mozambique Metical (MZM)'),
    'MMK' => t('Myanmar Kyat (MMK)'),
    'NAD' => t('Namibian Dollar (NAD)'),
    'NPR' => t('Nepalese Rupee (NPR)'),
    'ANG' => t('Neth Antilles Guilder (ANG)'),
    'NZD' => t('New Zealand Dollar (NZD)'),
    'NIO' => t('Nicaragua Cordoba (NIO)'),
    'NGN' => t('Nigerian Naira (NGN)'),
    'KPW' => t('North Korean Won (KPW)'),
    'NOK' => t('Norwegian Krone (NOK)'),
    'OMR' => t('Omani Rial (OMR)'),
    'XPF' => t('Pacific Franc (XPF)'),
    'PKR' => t('Pakistani Rupee (PKR)'),
    'XPD' => t('Palladium Ounces (XPD)'),
    'PAB' => t('Panama Balboa (PAB)'),
    'PGK' => t('Papua New Guinea Kina (PGK)'),
    'PYG' => t('Paraguayan Guarani (PYG)'),
    'PEN' => t('Peruvian Nuevo Sol (PEN)'),
    'PHP' => t('Philippine Peso (PHP)'),
    'XPT' => t('Platinum Ounces (XPT)'),
    'PLN' => t('Polish Zloty (PLN)'),
    'QAR' => t('Qatar Rial (QAR)'),
    'ROL' => t('Romanian Leu (ROL)'),
    'RUB' => t('Russian Rouble (RUB)'),
    'RWF' => t('Rwanda Franc (RWF)'),
    'WST' => t('Samoa Tala (WST)'),
    'STD' => t('Sao Tome Dobra (STD)'),
    'SAR' => t('Saudi Arabian Riyal (SAR)'),
    'SCR' => t('Seychelles Rupee (SCR)'),
    'SLL' => t('Sierra Leone Leone (SLL)'),
    'XAG' => t('Silver Ounces (XAG)'),
    'SGD' => t('Singapore Dollar (SGD)'),
    'SKK' => t('Slovak Koruna (SKK)'),
    'SIT' => t('Slovenian Tolar (SIT)'),
    'SBD' => t('Solomon Islands Dollar (SBD)'),
    'SOS' => t('Somali Shilling (SOS)'),
    'ZAR' => t('South African Rand (ZAR)'),
    'LKR' => t('Sri Lanka Rupee (LKR)'),
    'SHP' => t('St Helena Pound (SHP)'),
    'SDD' => t('Sudanese Dinar (SDD)'),
    'SRG' => t('Surinam Guilder (SRG)'),
    'SZL' => t('Swaziland Lilageni (SZL)'),
    'SEK' => t('Swedish Krona (SEK)'),
    'CHF' => t('Swiss Franc (CHF)'),
    'SYP' => t('Syrian Pound (SYP)'),
    'TWD' => t('Taiwan Dollar (TWD)'),
    'TZS' => t('Tanzanian Shilling (TZS)'),
    'THB' => t('Thai Baht (THB)'),
    'TOP' => t('Tonga Pa\'anga (TOP)'),
    'TTD' => t('Trinidad & Tobago Dollar (TTD)'),
    'TND' => t('Tunisian Dinar (TND)'),
    'TRL' => t('Turkish Lira (TRL)'),
    'USD' => t('U.S. Dollar (USD)'),
    'AED' => t('UAE Dirham (AED)'),
    'UGX' => t('Ugandan Shilling (UGX)'),
    'UAH' => t('Ukraine Hryvnia (UAH)'),
    'UYU' => t('Uruguayan New Peso (UYU)'),
    'VUV' => t('Vanuatu Vatu (VUV)'),
    'VEB' => t('Venezuelan Bolivar (VEB)'),
    'VND' => t('Vietnam Dong (VND)'),
    'YER' => t('Yemen Riyal (YER)'),
    'YUM' => t('Yugoslav Dinar (YUM)'),
    'ZMK' => t('Zambian Kwacha (ZMK)'),
    'ZWD' => t('Zimbabwe Dollar (ZWD)'),
  );

  return $currency;
}

function currency_api_get_fields($array) {
  while (list($field, $header) = each($array)) {
    $field_string = $field_string . $field;
  }
  
  return $field_string;
}

function _log_to_watchdog($msg = '', $severity = WATCHDOG_NOTICE, $type = 'user') {
  if (variable_get('currency_api_watchdog', 1)) {
    watchdog($type, $msg, $severity);
  }
}
