<?php
// $Id$

function autoloadtest_autoload_info() {
  return array(
    'AutoloadTestClass' => array(
      'file' => 'autoloadtest.classes.inc',
    ),
  );
}

function autoloadtest_autoload_info_alter($classes) {
  dpm($classes);
}


function autoloadtest_menu() {

  $items = array();

  $items['autoloadtest'] = array(
    'title' => 'Autoload test',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access content'),
    'page callback' => 'autoloadtest_page',
  );

  return $items;
}

function autoloadtest_page() {

  $test = new AutoloadTestClass();

  return $test->test();

}
