<?php
// $Id$

/**
 * @file
 * recipe_recipeML.module - Enables importing and exporting of recipeML format recipes.
 */

/**
 * Implementation of hook_recipeio($type).
 */
function recipe_recipeML_recipeio($type) {
  $supported = array(
    'export_single' => array(
      'format_name' => t('recipeML'),
      'callback' => 'recipe_recipeML_export_single',
      'format_help' => t('Export to a recipeML based xml format.')
    ),
    'export_multi' => array(
      'format_name' => t('recipeML'),
      'callback' => 'recipe_recipeML_export_multi',
      'format_help' => t('Export all recipes to recipeML based xml format.')
    )
  );
  return array('recipeml'=>$supported[$type]);
}

function recipe_recipeML_export_multi() {
  // you should not be able to export unpublished recipes
  $rs = db_query("SELECT n.nid from {node} n WHERE n.type='recipe' and n.status>0 ORDER BY n.title");

  $o = '<?xml version="1.0" encoding="UTF-8"?>'."\n".
  '<!DOCTYPE recipeml PUBLIC "-//FormatData//DTD RecipeML 0.5//EN" "http://www.formatdata.com/recipeml/recipeml.dtd">'."\n".
  '<recipeml version="0.5">'."\n";

  while ($row = db_fetch_object($rs)) {
    $o .= recipe_recipeML_export_single($row->nid, FALSE);
  }
  $o .= '</recipeml>';
  drupal_set_header('Content-type: text/xml');
  return $o;
}

function recipe_recipeML_export_single($nid = NULL, $add_content_header = TRUE) {
  if ( $nid === NULL ) {
    drupal_set_message(t('Recipe not found.'));
    drupal_not_found();
  }

  $node = node_load(array('nid' => $nid, 'type' => 'recipe'));
  // you should not be able to export unpublished recipes
  if ( $node->status == 0 ) {
    drupal_access_denied();
    return;
  }

  $vocabs = taxonomy_get_vocabularies('recipe');
  $cat_string = '';
  foreach ($vocabs as $vocab) {
    $terms = taxonomy_node_get_terms_by_vocabulary($node, $vocab->vid);
    foreach ( $terms as $term ) {
      $term = array_shift($terms);
      $cat_string .= $vocab->name .": ". $term->name . ', ';
    }
    $cat_string = substr($cat_string, 0, -2);
  }
  if ( $cat_string != '' ) {
    $cat_string = '<categories>'. $cat_string .'</categories>';
  }

  $output = '';
  if ( $add_content_header == TRUE ) {
    $output .= '<?xml version="1.0" encoding="UTF-8"?>'."\n".
    '<!DOCTYPE recipeml PUBLIC "-//FormatData//DTD RecipeML 0.5//EN" "http://www.formatdata.com/recipeml/recipeml.dtd">'."\n".
    '<recipeml version="0.5">'."\n";
  }

  $output .= '<recipe>'."\n".
    '<head>'."\n".
    '<title>'. my_xml_escape($node->title) .'</title>'."\n".$cat_string.
    '</head>'."\n".
    '<yield><qty>'. $node->yield .'</qty></yield>'."\n".
    '<ingredients>';

  foreach ($node->ingredients as $ingredient) {
    $output .= "\n".'<ing><amt><qty>'. $ingredient->quantity .'</qty><unit>'. $ingredient->abbreviation .'</unit></amt><item>'. $ingredient->name .'</item></ing>';
  }

  $output .= "\n".
    '</ingredients>'."\n".
    '<directions>'. my_xml_escape($node->instructions) .'</directions>'."\n".
    '</recipe>'."\n";


  if ( $add_content_header == TRUE) {
    $output .= '</recipeml>';
    drupal_set_header('Content-type: text/xml');
  }
  return $output;
}

function my_xml_escape($string) {
  $chars = array(
    '&'   => '&amp;',
    '<'   => '&lt;',
    '>'   => '&gt;',
    '"'   => '&quot;',
    '\''  => '&apos;'
  );
  return str_replace(array_keys($chars), array_values($chars), $string);
}
