<?php
// $Id$

/**
 * @file
 * recipe_plaintext.module - Support for the plaintext format input and output.
 *
 * Format Spec
 *
 *             Line1: TITLE
 *                    BLANK LINE
 * Ingredient Lines : <quantity> <unit> <ingredient>
 *                    ...
 *                    BLANK LINE
 * Instruction Lines: Freeform Instructions, blank lines ok from here on.
 */
 

/**
 * Implementation of hook_recipeio($type).
 */
function recipe_plaintext_recipeio($type) {
  $supported = array();
  switch ($type) {
    case 'import_single':
      $supported[] = array(
        'format_name' => t('Plain Text'),
        'callback' => 'recipe_import_parse_plain_text',
        'format_help' => ''
      );
    break;
  }
  return $supported;
}


/**
 * Parsing instance for plain text recipes
 */
function recipe_import_parse_plain_text($text) {
  // region constants
  define('TITLE', 0);
  define('INGREDIENTS', 1);
  define('DIRECTIONS', 2);

  $recipe = array();

  $region = TITLE;
  foreach (split("\n", $text) as $line) {
    $line = trim($line);
    if ( $region < DIRECTIONS && $line == '' ) {
      $region++;
      continue;
    }
    if ( $region == TITLE ) {
      $recipe['title'] = $line;
    }
    else if ( $region == INGREDIENTS ) {
      if ( preg_match('/^([0-9\-\.\/]+) +([A-Za-z\.]+) +(.*)/', $line, $matches)  ) {
        $i = array();
        $i['quantity'] = $matches[1];
        $i['unit_name'] = $matches[2];
        $i['ingredient_name'] = $matches[3];

        // FALSE if no-match
        $i['unit_obj'] = recipe_unit_fuzzymatch($i['unit_name']);

        // FALSE if no-match
        $i['ingred_obj'] = recipe_ingredient_match($i['ingredient_name']);

        $recipe['ingredients'][] = $i;
      }
      else {
        $i = array();
        $i['quantity'] = 0;
        $i['unit_name'] = 'Unit';
        $i['ingredient_name'] = "failed: " . $line;
        $i['unit_obj'] = FALSE;
        $i['ingred_obj'] = FALSE;
        $recipe['ingredients'][] = $i;
      }
    }
    else if ( $region == DIRECTIONS ) {
      $recipe['instructions'] .= $line ."\n";
    }
  }
  return $recipe;
}
