<?php
// $Id$

/**
 * @file
 * recipe_mastercook4.module - Enables importing and exporting of MasterCook4 format recipes.
 */

/**
 * Implementation of hook_recipeio($type).
 */
function recipe_mastercook4_recipeio($type) {
  $supported = array();
  switch ($type) {
    case 'export_single':
      // Key here must be lower case and not use any url special chars
      $supported['mastercook4'] = array(
        'format_name' => t('MasterCook4'),
        'callback' => 'recipe_mastercook4_export',
        'format_help' => t('Export to a MasterCook4 based text format.')
      );
    break;
  }
  return $supported;
}


function recipe_mastercook4_export($nid = NULL) {
  if ( $nid === NULL ) {
    drupal_set_message(t('Recipe not found.'));
    drupal_not_found();
  }

  $node = node_load(array('nid' => $nid, 'type' => 'recipe'));
  
  $decimal_hours = $node->preptime/60;
  $hours = floor($decimal_hours);
  $minutes = sprintf("%02d",floor(($decimal_hours - $hours)*60));

	// need to work on the category wrapping
  $categories = '';
  $vocabs = taxonomy_get_vocabularies('recipe');
  foreach ($vocabs as $vocab) {
    $terms = taxonomy_node_get_terms_by_vocabulary($node, $vocab->vid);
    foreach ( $terms as $term ) {
      $term = array_shift($terms);
      $categories .= sprintf("%-33s", $term->name);
    }
  }
  $categories = wordwrap($categories, 66, "\n                ");

  $o = "                     *  Exported from  MasterCook  *\n";
  $o .= "\n";
  $o .= $node->title . "\n";
  $o .= "\n";
  $o .= "Recipe By     : " . $node->source . "\n";  
  $o .= "Serving Size  : " . $node->yield . "    Preparation Time :$hours:$minutes\n";
  $o .= "Categories    : $categories\n\n";
  $o .= "  Amount  Measure       Ingredient -- Preparation Method\n";
  $o .= "--------  ------------  --------------------------------\n";
  
  foreach ( $node->ingredients as $key => $i ) {
    $o .= format_mastercook4_ingredient($i);
  }
  $o .= "\n";
  $o .= $node->instructions ."\n\n". $node->body ."\n\n". $node->notes . "\n";
  $o .= "\n";
  $o .= "                   - - - - - - - - - - - - - - - - - -\n";

  drupal_set_header('Content-type: text');
  return $o;
}

function format_mastercook4_ingredient($ingredient=NULL) {
	
  $ingredient->quantity = recipe_ingredient_quantity_from_decimal($ingredient->quantity);
  // no html entities
  $ingredient->quantity = str_replace('&frasl;', '/', $ingredient->quantity);
  $ingredient->unit_name = strtolower(recipe_unit_name($ingredient->unit_id));
	$o = sprintf("%8s  %-12s  %s\n", $ingredient->quantity, $ingredient->unit_name, $ingredient->name);
	
	return $o;
}
