<?php
// $Id$

/**
 * @file node_export_filefield.module
 *  Export helper module for handling CCK FileFields.
 */

/**
 * Implementation of hook_help().
 */
function node_export_filefield_help($path, $arg) {
  switch ($path) {
    case 'admin/help#node_export_filefield':
      return '<p>'. t('Export helper module for handling CCK FileFields.') .'</p>';
  }
}

/**
 * Implementation of hook_form_alter()
 */
function node_export_filefield_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_export_form') {
    $form['node_export_filefield'] = array(
      '#type' => 'checkbox',
      '#title' => t('Export Uploaded Files'),
      '#default_value' => variable_get('node_export_filefield_default', TRUE),
      '#description' => t(
        'When checked, all uploaded files will be copied to the
         assets directory and the export will be modified to keep
         track of this.  Currently the assets directory is set
         to <code>!assets</code>, change this on the !admin_page.',
        array(
          '!assets' => variable_get('node_export_filefield_assets_path', 'sites/all/assets'),
          '!admin_page' => l('admin page', 'admin/settings/node_export')
        )
      ),
      '#weight' => -10,
    );
    $form['node_export_filefield_copy'] = array(
      '#type' => 'submit',
      '#value' => t('Copy File Uploads to Assets Path'),
      '#weight' => -9,
    );
  } else if ($form_id == 'node_export_settings') {
    $form['node_export_filefield'] = array(
      '#type' => 'fieldset',
      '#title' => t('Export FileField'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#weight' => -1,
    );
    $form['node_export_filefield']['node_export_filefield_assets_path'] = array(
      '#type' => 'textfield',
      '#title' => t('Export FileField Assets Path'),
      '#size' => 60,
      '#maxlength' => 255,
      '#default_value' => variable_get('node_export_filefield_assets_path', 'sites/all/assets'),
      '#description' => t(
        'Path to copy file uploads to when the node is exported.
         This path can be committed to your SCM (eg: Subversion,
         CVS, git) for later importing.  <em>Tip: For install profile
         developers, setting this path to
         <code>profiles/my_profile/node_export_assets</code>
         may be useful.</em>'
      ),
      '#required' => FALSE,
    );
    $form['node_export_filefield']['node_export_filefield_default'] = array(
      '#type' => 'checkbox',
      '#title' => t('Export FileField Uploads by Default?'),
      '#default_value' => variable_get('node_export_filefield_default', TRUE),
    );
  }
}

/**
 * Implementation of hook_export_node_alter()
 **/
function node_export_filefield_export_node_alter(&$node, $original_node, $method) {
  if ($method == 'export') {
    $do_copy = FALSE; // Copy assets?
    $assets_path = variable_get('node_export_filefield_assets_path', 'sites/all/assets');

    // If the "Copy File Uploads to Assets Path" button was clicked
    if ($_POST['node_export_filefield'] == 1) {
      // Ensure the assets path is set
      if (!is_dir($assets_path) && mkdir($assets_path, 0777, TRUE) == FALSE) {
        drupal_set_message(t("Could not create assets path! '$assets_path'"), 'error');
        return FALSE;
      }

      $do_copy = TRUE;
    }

    foreach ($node as $attr => $value) {
      $field = &$node->$attr;

      $file = _node_export_filefield_is_filefield($attr, $field);

      if ($file == FALSE) {
        continue;
      }
      else if (is_file($file->filepath)) {
        $export_filepath = $assets_path . '/' . basename($file->filepath);

        if ($do_copy) {
          copy($file->filepath, $export_filepath);
        }

        // Ensure the file already exists in the assets path, or has been
        // sucessfully copied
        if (is_file($export_filepath)) {
          $field[0]['export_filepath'] = $export_filepath;
        }
        else {
          drupal_set_message(t("CCK file upload '!path' is NOT in assets path, please press 'Copy File Uploads to Assets Path'.", array('!path' => $file->filepath)), 'error');
        }
      }
      else {
        drupal_set_message(t("CCK file upload found on node, but doesn't exist on disk? '!path'", array('!path' => $file->filepath)), 'error');
      }
    }
  }
  // Attempt to reattach CCK file uploads
  else if ($method == 'save-edit') {
    foreach ($node as $attr => $value) {
      $field = &$node->$attr;

      $file = _node_export_filefield_is_filefield($attr, $field);

      if ($file == FALSE) {
        continue;
      }

      // The file is already in the right location
      if (is_file($file->filepath)) {
        drupal_write_record('files', $file);
      }
      // The file is in an "assets" location, move it to the
      // destination then finish the save
      else if (isset($file->export_filepath) && is_file($file->export_filepath)) {
        $directory = file_create_path(dirname($file->filepath));

        if (file_check_directory($directory, TRUE)) {
          file_copy($file->export_filepath, $directory, FILE_EXISTS_REPLACE);

          $file->filepath = $file->export_filepath;
          unset($file->export_filepath);

          drupal_write_record('files', $file);
        }
      }

      // The file was saved successfully, update the CCK field (by reference)
      if (isset($file->fid)) {
        $field[0]['fid'] = $file->fid;
      }
    }
  }
}

/**
 * Determines if a node attribute is a filefield.
 * 
 * If YES, the field is returned as a Drupal file object.  If NO, FALSE
 * is returned.
 **/
function _node_export_filefield_is_filefield($attribute, $field) {
  // Skip non-CCK attributes
  if (substr($attribute, 0, 6) != 'field_') {
    return FALSE;
  }

  if (isset($field[0]['fid'])) {
    $file = (object) $field[0];
    unset($file->fid);
  } else {
    return FALSE;
  }

  // Doesn't look like a file, move on
  if (!isset($file->filepath)) {
    return FALSE;
  }

  return $file;
}
