<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function file_aliases_menu() {
  $items['filefield_paths/alias/%'] = array(
    'page callback' => 'file_aliases_load_fid',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_filefield_paths_field_settings().
 */
function file_aliases_filefield_paths_field_settings() {
  return array(
    'file_alias' => array(
      'title' => 'File alias',
      'sql' => 'filealias',

      'data' => array('display' => 'file_alias_display'),

      'form' => array(
        'file_alias' => array(
          '#type' => 'textfield',
          '#title' => t('File alias'),
          '#default_value' => '',
        ),

        'file_alias_display' => array(
          '#type' => 'checkbox',
          '#title' => t('Display alias'),
          '#description' => t('If checked, the file alias will be displayed instead of the file') .'.',
          '#default_value' => 0,
          '#weight' => 3
        ),
      ),
    )
  );
}

/**
 * Implementation of hook_filefield_paths_process_file().
 */
function file_aliases_filefield_paths_process_file($new, $file, $settings, $node, $update) {
  if ($new) {
    $file['filealias'] = filefield_paths_process_string($settings['filealias']['value'], 'node', $node, $settings['filealias']);
    $file['filealias'] = filefield_paths_process_string($file['filealias'], 'field', array(0 => $file['field']), $settings['filealias']);

    path_set_alias('filefield_paths/alias/'. $file['field']['fid'], $file['filealias']);
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function file_aliases_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'load':
      if (($ffp = filefield_paths_get_fields($node, $op)) == FALSE) {
        break;
      }

      foreach ($ffp['#files'] as &$file) {
        if ($ffp['#settings'][$file['name']]['filealias']['display'] == TRUE) {
          $filefield_paths_alias = 'filefield_paths/alias/'. $file['field']['fid'];
          if (($alias = drupal_get_path_alias($filefield_paths_alias)) != $filefield_paths_alias) {
            $relative_dir = '';
            foreach (explode('/', file_directory_path()) as $dir) {
              $relative_dir .= '../';
            }

            $file['field']['filepath'] = $relative_dir . $alias;
            $file['field']['filename'] = array_pop(explode('/', $alias));
          }
        }
      }
      break;

  }
}

function file_aliases_load_fid($fid) {
  if ($_SERVER['REQUEST_URI'] == '/filefield_paths/alias/'. $fid) {
    drupal_not_found();
    exit;
  }

  $result = db_fetch_object(db_query("SELECT filemime, filepath FROM {files} WHERE fid = %d", $fid));

  header('Content-Type: '. $result->filemime);
  readfile($result->filepath);
}
