<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function xmlsitemap_engines_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/settings/xmlsitemap/engines':
      $output .= t('In order to verify site ownership with the search engines listed below, it is highly recommended to download and install the <a href="@site-verify">Site verification module</a>.', array('@site-verify' => 'http://drupal.org/project/site_verify'));
      break;
  }

  return $output;
}

/**
 * Implementation of hook_menu().
 */
function xmlsitemap_engines_menu() {
  $items['admin/settings/xmlsitemap/engines'] = array(
    'title' => 'Search Engines',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xmlsitemap_engines_settings_form'),
    'access arguments' => array('administer xmlsitemap'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'xmlsitemap_engines.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_cron().
 */
function xmlsitemap_engines_cron() {
  if (variable_get('site_offline', 0)
      || (xmlsitemap_engines_var('submit_updated') && xmlsitemap_var('generated_last') < xmlsitemap_engines_var('submit_last'))
      || (REQUEST_TIME - xmlsitemap_engines_var('submit_last')) < xmlsitemap_engines_var('minimum_lifetime')) {
    return;
  }

  $sitemaps = xmlsitemap_get_sitemaps();
  $engines = xmlsitemap_engines_var('engines');
  foreach ($engines as $engine) {
    foreach ($sitemaps as $sitemap) {
      $url = xmlsitemap_engines_prepare_url(xmlsitemap_engines_get_engines($engine, 'url'), $sitemap);
      $request = drupal_http_request($url);
      watchdog('xmlsitemap', 'Submitted the sitemap to %url and received response @code.', array('%url' => $url, '@code' => $request->code));
    }
  }

  $custom_urls = xmlsitemap_engines_var('custom_urls');
  $custom_urls = preg_split('/[\r\n]+/', $custom_urls, -1, PREG_SPLIT_NO_EMPTY);
  foreach ($custom_urls as $custom_url) {
    foreach ($sitemaps as $sitemap) {
      $url = xmlsitemap_engines_prepare_url($custom_url, $sitemap);
      $request = drupal_http_request($url);
      watchdog('xmlsitemap', 'Submitted the sitemap to %url and received response @code.', array('%url' => $url, '@code' => $request->code));
    }
  }

  variable_set('xmlsitemap_engines_submit_last', REQUEST_TIME);
}

/**
 * Replace valid tokens in the URL with their appropriate values.
 *
 * @param $url
 *   An un-tokenized URL.
 * @return
 *   A tokenized URL.
 */
function xmlsitemap_engines_prepare_url($url, $sitemap) {
  return str_replace('[sitemap]', $sitemap, $url);
}

/**
 * Get a list of supported search engines, or a detail about a specific engine.
 *
 * @param $engine
 *   An optional specific engine to get details about.
 * @param $value
 *   An optional value about an engine to get details about.
 * @return
 *   If $engine and $value are not specified, a two-level array with all the
 *   engines and their details. If $engine is specified but $value is not, an
 *   array with just the details for a specific engine. If $engine and $value
 *   are both specified, just the specific detail for a specific engine.
 */
function xmlsitemap_engines_get_engines($engine = NULL, $value = NULL) {
  static $engines;

  if (!isset($engines)) {
    $engines = array(
      'google' => array(
        'name' => t('Google'),
        'url' => 'http://www.google.com/webmasters/tools/ping?sitemap=[sitemap]',
      ),
      'yahoo' => array(
        'name' => t('Yahoo!'),
        'url' => 'http://search.yahooapis.com/SiteExplorerService/V1/ping?sitemap=[sitemap]',
      ),
      'ask' => array(
        'name' => t('Ask.com'),
        'url' => 'http://submissions.ask.com/ping?sitemap=[sitemap]',
      ),
      'bing' => array(
        'name' => t('Bing (formerly Live Search)'),
        'url' => 'http://www.bing.com/webmaster/ping.aspx?siteMap=[sitemap]',
      ),
      'moreover' => array(
        'name' => t('Moreover'),
        'url' => 'http://api.moreover.com/ping?u=[sitemap]',
      ),
    );

    // Allow other modules to alter or add search engines.
    drupal_alter('xmlsitemap_engines', $engines);
    ksort($engines);
  }

  if (isset($engine) && isset($value)) {
    return isset($engines[$engine][$value]) ? $engines[$engine][$value] : NULL;
  }
  elseif (isset($engine)) {
    return isset($engines[$engine]) ? $engines[$engine] : NULL;
  }
  else {
    return $engines;
  }
}

/**
 * Internal default variables for template_var().
 */
function xmlsitemap_engines_variables() {
  $variables = array(
    'xmlsitemap_engines_engines' => array(),
    'xmlsitemap_engines_custom_urls' => '',
    'xmlsitemap_engines_minimum_lifetime' => 3600,
    'xmlsitemap_engines_submit_last' => 0,
    'xmlsitemap_engines_submit_updated' => TRUE,
  );

  return $variables;
}

/**
 * Internal implementation of variable_get().
 */
function xmlsitemap_engines_var($name, $default = NULL) {
  static $defaults = NULL;
  if (!isset($defaults)) {
    $defaults = xmlsitemap_engines_variables();
  }

  $name = 'xmlsitemap_engines_' . $name;

  // @todo Remove when stable.
  if (!isset($defaults[$name])) {
    trigger_error(t('Default variable for %variable not found.', array('%variable' => $name)));
  }

  return variable_get($name, isset($default) || !isset($defaults[$name]) ? $default : $defaults[$name]);
}
