<?php
// $Id$

/*****************************************************************************
 * Drupal hooks.
 ****************************************************************************/

/**
 * Implementation of hook_update_N().
 */
function xmlsitemap_engines_update_6100() {
  return array();
}

/**
 * Implementation of hook_uninstall().
 */
function xmlsitemap_engines_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'xmlsitemap\_engines\_'");
}
