<?php
// $Id$

/**
 * Implementation of hook_cron().
 *
 * Process old menu links not found in the {xmlsitemap} table.
 */
function xmlsitemap_menu_cron() {
  if ($menus = xmlsitemap_menu_var('menus')) {
    // Set the global user variable to the anonymous user.
    xmlsitemap_switch_user(0);

    $sql = "SELECT ml.mlid FROM {menu_links} ml LEFT JOIN {xmlsitemap} x ON x.type = 'menu' AND ml.mlid = x.id WHERE (x.id IS NULL OR x.status IS NULL) AND ml.menu_name IN (" . db_placeholders($menus, 'varchar') . ")";
    $query = db_query_range($sql, $menus, 0, xmlsitemap_var('batch_limit'));

    while ($mlid = db_result($query)) {
      $menu_item = menu_link_load($mlid);
      $link = xmlsitemap_menu_create_link($menu_item);
      xmlsitemap_save_link($link);
    }

    // Set the global user variable back to the original user.
    xmlsitemap_restore_user();
  }
}

/**
 * Implementation of hook_xmlsitemap_links().
 */
function xmlsitemap_menu_xmlsitemap_links($offset = 0, $limit = 0) {
  $links = array();

  if ($menus = xmlsitemap_menu_var('menus')) {
    // Set the global user variable to the anonymous user.
    xmlsitemap_switch_user(0);

    $sql = "SELECT ml.mlid FROM {menu_links} ml WHERE ml.mlid > %d AND ml.menu_name IN (" . db_placeholders($menus, 'varchar') . ") ORDER BY ml.mlid";
    $args = array_merge(array($offset), $menus);
    $query = ($limit ? db_query_range($sql, $args, 0, $limit) : db_query($sql, $args));

    while ($mlid = db_result($query)) {
      $menu_item = menu_link_load($mlid);
      $links[] = xmlsitemap_menu_create_link($menu_item);
    }

    // Set the global user variable back to the original user.
    xmlsitemap_restore_user();
  }

  return $links;
}

/**
 * Implementation of hook_xmlsitemap_links_batch_info().
 */
function xmlsitemap_menu_xmlsitemap_links_batch_info() {
  $menus = xmlsitemap_menu_var('menus');
  return array(
    'max' => $menus ? db_result(db_query("SELECT COUNT(ml.mlid) FROM {menu_links} ml WHERE ml.menu_name IN (" . db_placeholders($menus, 'varchar') . ")", $menus)) : 0,
  );
}

/**
 * Implementation of hook_xmlsitemap_links_clear().
 */
function xmlsitemap_menu_xmlsitemap_links_clear() {
  db_query("DELETE FROM {xmlsitemap} WHERE type = 'menu'");
}

function xmlsitemap_menu_form_alter(&$form, $form_state, $form_id) {
  //dpm ($form_id);
}

function xmlsitemap_menu_form_menu_overview_form_alter(&$form, $form_state) {
  $form['#submit'][] = 'xmlsitemap_menu_menu_overview_form_submit';
}

function xmlsitemap_menu_menu_overview_form_submit($form, $form_state) {
  foreach (element_children($form) as $mlid) {
    if (isset($form[$mlid]['#item'])) {
      xmlsitemap_switch_user(0);
      $menu_item = menu_link_load($form[$mlid]['#item']['mlid']);
      xmlsitemap_restore_user();
      xmlsitemap_menu_item_update($menu_item);
    }
  }
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function xmlsitemap_menu_form_menu_item_delete_form_alter(&$form, $form_state) {
  $form['#submit'][] = 'xmlsitemap_menu_menu_item_delete_form_submit';
}

function xmlsitemap_menu_menu_item_delete_form_submit($form, $form_state) {
  xmlsitemap_menu_item_delete($form['#item']);
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function xmlsitemap_menu_form_menu_edit_item_alter(&$form, $form_state) {
  $form['#submit'][] = 'xmlsitemap_menu_menu_edit_item_submit';
}

function xmlsitemap_menu_menu_edit_item_submit($form, $form_state) {
  xmlsitemap_switch_user(0);
  $menu_item = menu_link_load($form_state['values']['menu']['mlid']);
  xmlsitemap_restore_user();
  xmlsitemap_menu_item_update($menu_item);
}

function xmlsitemap_menu_item_update($menu_item) {
  $link = xmlsitemap_menu_create_link($menu_item);
  xmlsitemap_save_link($link);
}

function xmlsitemap_menu_item_delete($menu_item) {
  xmlsitemap_delete_link(array('type' => 'menu', 'id' => $menu_item['mlid']));
}

/**
 * Create a sitemap link from a menu item.
 *
 * @param $menu_item
 *   A loaded menu item.
 */
function xmlsitemap_menu_create_link($menu_item) {
  static $menus;

  if (!isset($menus)) {
    $menus = xmlsitemap_menu_var('menus');
  }

  return array(
    'type' => 'menu',
    'id' => $menu_item['mlid'],
    'loc' => $menu_item['link_path'],
    'priority' => xmlsitemap_menu_get_priority($menu_item),
    'status' => $menu_item['access'] && !$menu_item['external'] && !$menu_item['hidden'] && in_array($menu_item['menu_name'], $menus),
    'menu_name' => $menu_item['menu_name'],
  );
}

/**
 * Calculate the priority of a menu link.
 */
function xmlsitemap_menu_get_priority($menu_item) {
  if (xmlsitemap_menu_var('calculate_priority')) {
    $priority = (MENU_MAX_DEPTH - $menu_item['depth'] + 1) / MENU_MAX_DEPTH;
    $priority -= (50 + $menu_item['weight']) / (100 * (MENU_MAX_DEPTH + 1));
    return $priority;
  }
  else {
    return NULL;
  }
}

/**
 * Implementation of hok_form_FORM_ID_alter().
 */
function xmlsitemap_menu_form_xmlsitemap_settings_form_alter(&$form, $form_state) {
  $form['menu'] = array(
    '#type' => 'fieldset',
    '#title' => t('Menus'),
    '#collapsible' => TRUE,
    '#collapsed' => !xmlsitemap_menu_var('menus'),
  );

  $header = array(
    t('Menu'),
    t('Included in sitemap?'),
    t('Default priority'),
  );
  $rows = array();
  $menus = menu_get_menus();
  foreach ($menus as $menu => $name) {
    $status = variable_get('xmlsitemap_menu_status_' . $menu, FALSE);
    $priority = variable_get('xmlsitemap_menu_priority_' . $menu, 'default');
    $rows[] = array(
      l($name, 'admin/build/menu-customize/' . $menu . '/edit', array('query' => drupal_get_destination())),
      $status ? t('Included') : t('Not included'),
      t($priority),
    );
  }
  $form['menu']['menu_list'] = array(
    '#value' => theme('table', $header, $rows),
    '#access' => FALSE,
  );

  $form['menu']['xmlsitemap_menu_menus'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Menus to include in the sitemap'),
    '#options' => menu_get_menus(),
    '#default_value' => xmlsitemap_menu_var('menus'),
    '#suffix' => '<hr />',
  );
  $form['menu']['xmlsitemap_menu_calculate_priority'] = array(
    '#type' => 'checkbox',
    '#title' => t('Calculate priority based on menu item depth and weight.'),
    '#default_value' => xmlsitemap_menu_var('calculate_priority'),
  );

  array_unshift($form['#submit'], 'xmlsitemap_menu_settings_form_submit');
}

/**
 * Submit handler; Remove links from de-selected menus.
 */
function xmlsitemap_menu_settings_form_submit($form, $form_state) {
  $current_menus = xmlsitemap_menu_var('menus');
  $selected_menus = $form_state['values']['xmlsitemap_menu_menus'];
  $removed_menus = array_diff($current_menus, $selected_menus);

  foreach ($removed_menus as $removed_menu) {
    db_query("DELETE FROM {xmlsitemap} WHERE id IN (SELECT mlid FROM {menu_links} WHERE menu_name = '%s') AND type = 'menu'", $removed_menu);
  }
}

/**
 * Internal default variables for template_var().
 */
function xmlsitemap_menu_variables() {
  return array(
    'xmlsitemap_menu_menus' => array(),
    'xmlsitemap_menu_calculate_priority' => FALSE,
  );
}

/**
 * Internal implementation of variable_get().
 */
function xmlsitemap_menu_var($name, $default = NULL) {
  static $defaults = NULL;
  if (!isset($defaults)) {
    $defaults = xmlsitemap_menu_variables();
  }

  $name = 'xmlsitemap_menu_'. $name;

  // @todo Remove when stable.
  if (!isset($defaults[$name])) {
    trigger_error(t('Default variable for %variable not found.', array('%variable' => $name)));
  }

  return variable_get($name, isset($default) || !isset($defaults[$name]) ? $default : $defaults[$name]);
}
