<?php
// $Id$
/**
 * @author Services Dev Team
 * @file
 *  Link general user functionalities to services module.
 */

/**
 * Implementation of hook_help().
 */
function user_service_help($path, $arg) {
  switch ($path) {
    case 'admin/help#services_user':
      return t('<p>Provides user methods to services applications.  Requires services.module.</p>');
    case 'admin/modules#description':
      return t('Provides user methods to services applications.  Requires services.module.');
  }
}

/**
 * Implementation of hook_service().
 */
function user_service_service() {
  return array(

    // user.login
    array(
      '#method'           => 'user.login',
      '#callback'         => 'user_service_login',
      '#file'             => array('file' => 'inc', 'module' => 'user_service'),
      '#args'             => array(
        array(
          '#name'           => 'username',
          '#type'           => 'string',
          '#description'    => t('A valid username.'),
        ),
        array(
          '#name'           => 'password',
          '#type'           => 'string',
          '#description'    => t('A valid password.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Logs in a user.')
    ),

    // user.logout
    array(
      '#method'           => 'user.logout',
      '#callback'         => 'user_service_logout',
      '#file'             => array('file' => 'inc', 'module' => 'user_service'),
      '#args'             => array(),
      '#return'           => 'struct',
      '#help'             => t('Logs out a user.')
    ),

    // user.get
    array(
      '#method'           => 'user.get',
      '#callback'         => 'user_service_get',
      '#file'             => array('file' => 'inc', 'module' => 'user_service'),
      '#args'             => array(
        array(
          '#name'           => 'uid',
          '#type'           => 'int',
          '#description'    => t('User ID.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Get all user details.')
    ),


    // user.save
    array(
      '#method'           => 'user.save',
      '#callback'         => 'user_service_save',
      '#file'             => array('file' => 'inc', 'module' => 'user_service'),
      '#args'             => array(
        array(
          '#name'           => 'uid',
          '#type'           => 'int',
          '#description'    => t('User ID.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Save user details.')
    ),


    // user.delete
    array(
      '#method'           => 'user.delete',
      '#callback'         => 'user_service_delete',
      '#file'             => array('file' => 'inc', 'module' => 'user_service'),
      '#args'             => array(
        array(
          '#name'           => 'uid',
          '#type'           => 'int',
          '#description'    => t('User ID.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Delete an user.')
    ),
  );
}
