<?php
// $Id$

/**
 * @file
 * Adds user profiles to the site map.
 */

/**
 * @addtogroup xmlsitemap
 * @{
 */

/*****************************************************************************
 * Drupal hooks.
 ****************************************************************************/

/**
 * Implementation of hook_form_alter().
 */
function xmlsitemap_user_form_alter($form_id, &$form) {
  switch ($form_id) {
    case 'user_admin_settings':
      $form['xmlsitemap_user'] = array(
        '#type' => 'fieldset',
        '#title' => t('XML site map'),
        '#collapsible' => TRUE,
      );
      $default = variable_get('xmlsitemap_user_default_priority', 0.5);
      $form['xmlsitemap_user']['xmlsitemap_user_old_default_priority'] = array(
        '#type' => 'value',
        '#value' => $default
      );
      $form['xmlsitemap_user']['xmlsitemap_user_default_priority'] = array(
        '#type' => 'select',
        '#title' => t('Default user priority'),
        '#default_value' => $default,
        '#options' => xmlsitemap_priority_options('exclude'),
        '#description' => t('Choose the default priority for users who have only the authenticated user role.'),
      );
      $form['buttons']['#weight'] = 1;
      $form['#submit'][] = 'xmlsitemap_user_form_submit';
      break;
    case 'user_admin_role':
      $options = xmlsitemap_priority_options('exclude');
      $priority = db_result(db_query("SELECT priority
        FROM {xmlsitemap_user_role}
        WHERE rid = %d", $form['rid']['#value'])
      );
      if ($priority === FALSE) {
        $priority = 0.5;
      }
      $form['xmlsitemap_user'] = array(
        '#type' => 'fieldset',
        '#title' => t('XML site map'),
        '#collapsible' => TRUE,
      );
      $form['xmlsitemap_user']['xmlsitemap_user_role_priority'] = array(
        '#type' => 'select',
        '#title' => t('Default priority'),
        '#default_value' => $priority,
        '#options' => $options,
        '#description' => t("The priority of all a user's roles will be added together to set the user's default priority. If all role priorities are left at default, the user's default priority will be %priority.", array('%priority' => $options[variable_get('xmlsitemap_user_default_priority', '0.5')])),
      );
      $form['submit']['#weight'] = 1;
      $form['delete']['#weight'] = 1;
      $form['#submit'][] = 'xmlsitemap_user_form_submit';
      break;
  }
}

/**
 * Implementation of hook_perm().
 */
function xmlsitemap_user_perm() {
  return array('override profile priority');
}

/**
 * Implementation of hook_user().
 */
function xmlsitemap_user_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'form':
      if ($category != 'account') {
        return array();
      }
    case 'register':
      $priority = db_result(db_query("SELECT priority_override
        FROM {xmlsitemap_user}
        WHERE uid = %d", $account->uid)
      );
      if (user_access('override profile priority')) {
        $form['xmlsitemap_user'] = array(
          '#type' => 'fieldset',
          '#title' => t('XML site map'),
          '#collapsible' => TRUE,
          '#weight' => 7,
        );
        $options = xmlsitemap_priority_options('both');
        if (isset($account->roles)) {
          $roles = array_keys($account->roles);
          $default = db_fetch_object(
            db_query("SELECT MIN(priority) AS min, SUM(priority) AS sum
              FROM {xmlsitemap_user_role}
              WHERE rid IN (". db_placeholders($roles, 'varchar') .")",
              $roles
            )
          );
        }
        if (isset($default->min) && isset($default->sum)) {
          $default_priority = $default->min < 0 ? -1.0 : round(min($default->sum, 1), 1);
        }
        else {
          $default_priority = variable_get('xmlsitemap_user_default_priority', 0.5);
        }
        $form['xmlsitemap_user']['xmlsitemap_user_priority'] = array(
          '#type' => 'select',
          '#title' => t('Priority'),
          '#default_value' => $priority !== FALSE ? $priority : -2.0,
          '#options' => $options,
          '#description' => t('The default priority is %priority.', array('%priority' => $options[(string)$default_priority])),
        );
      }
      else {
        $form['xmlsitemap_user_priority'] = array(
          '#type' => 'value',
          '#value' => $priority !== FALSE ? $priority : -2.0
        );
      }
      return $form;
    case 'insert':
      $row = new stdClass();
      $row->uid = $account->uid;
      $row->changed = time();
      if ($edit['xmlsitemap_user_priority'] != -2.0) {
        $row->priority_override = $edit['xmlsitemap_user_priority'];
      }
      drupal_write_record('xmlsitemap_user', $row);
      $edit['xmlsitemap_user_priority'] = NULL;
      xmlsitemap_update_sitemap();
      break;
    case 'update':
      if (($result = db_fetch_object(db_query("SELECT * FROM {xmlsitemap_user} WHERE uid = %d", $account->uid))) === FALSE) {
        $row = new stdClass();
        $row->uid = $account->uid;
        $row->changed = time();
      }
      else {
        $row = $result;
        $row->previously_changed = $row->changed;
        $row->changed = time();
      }
      if ($edit['xmlsitemap_user_priority'] != -2.0) {
        $row->priority_override = $edit['xmlsitemap_user_priority'];
      }
      drupal_write_record('xmlsitemap_user', $row, $result !== FALSE ? 'uid' : NULL);
      $edit['xmlsitemap_user_priority'] = NULL;
      xmlsitemap_update_sitemap();
      break;
    case 'delete':
      db_query("DELETE FROM {xmlsitemap_user} WHERE uid = %d", $account->uid);
      xmlsitemap_update_sitemap();
      break;
  }
}

/**
 * Implementation of hook_xmlsitemap_database_batch_operation().
 */
function xmlsitemap_user_xmlsitemap_database_batch_operation() {
  return array(
    'add function' => 'xmlsitemap_user_update_database',
  );
}

/**
 * Implementation of hook_xmlsitemap_description().
 */
function xmlsitemap_user_xmlsitemap_description() {
  return '<dt>'. t('XML Sitemap: User') .'</dt>'.
    '<dd>'. t('<em>XML Sitemap: User</em> adds user profiles to the site map. The <em>anonymous user</em> role must be given permission to access user profiles on the <a href="@access">access control page</a>. You can change the default user priority on the <a href="@user_settings">user settings</a> page. The <a href="@user">user role priority</a> will override the default user priority. You can override both the default priority and the role priority when you add or edit a user.', array('@access' => url('admin/user/access'), '@user_settings' => url('admin/user/settings'), '@user_role' => url('admin/user/roles'))) .'</dd>';
}

/**
 * Implementation of hook_xmlsitemap_links().
 */
function xmlsitemap_user_xmlsitemap_links() {
  if (user_access('access user profiles')) {
    switch ($GLOBALS['db_type']) {
      case 'mysql':
      case 'mysqli':
        $coalesce = 'COALESCE';
        $cast = 'CHAR';
        break;
      case 'pgsql':
        $coalesce = 'FIRST';
        $cast = 'VARCHAR';
        break;
    }
    $uid = 0;
    $frontpage = explode('/', drupal_get_normal_path(variable_get('site_frontpage', 'node')));
    if (count($frontpage) == 2 && $frontpage[0] == 'user' && is_numeric($frontpage[1])) {
      $uid = $frontpage[1];
    }
    $columns = 'u.uid, xu.changed, xu.previously_changed, xu.priority_override, SUM(xur.priority) as priority';
    $result = db_query("SELECT $columns, $coalesce(ua.dst) AS alias
      FROM {xmlsitemap_user} xu
      INNER JOIN {users} u ON xu.uid = u.uid
      LEFT JOIN {users_roles} ur ON xu.uid = ur.uid
      LEFT JOIN {xmlsitemap_user_role} xur ON ur.rid = xur.rid
      LEFT JOIN {url_alias} ua ON ua.src = CONCAT('user/', CAST(u.uid AS $cast))
      WHERE u.status <> 0
        AND u.uid <> %d
      GROUP BY $columns
      HAVING MIN(xur.priority) <> -1 OR SUM(xur.priority) IS NULL",
      $uid
    );
    while ($user = db_fetch_object($result)) {
      $age = time() - $user->changed;
      $interval = $user->previously_changed ? $user->changed - $user->previously_changed : 0;
      if ($user->priority_override != -2.0) {
        $priority = $user->priority_override;
      }
      else {
        $priority = min(isset($user->priority) ? $user->priority : variable_get('xmlsitemap_user_default_priority', 0.5), 1);
      }
      db_query("INSERT INTO {xmlsitemap} (loc, lastmod, changefreq, priority) VALUES ('%s', %d, %d, %f)",
        xmlsitemap_url('user/'. $user->uid, $user->alias, NULL, NULL, TRUE),
        $user->changed, max($age, $interval), $priority);
    }
  }
}

/*****************************************************************************
 * Menu callbacks / form builders, submit/validate functions.
 ****************************************************************************/

/**
 * Form submit function.
 */
function xmlsitemap_user_form_submit($form, &$form_state) {
  $form_values = $form_state['values'];
  $form_id = $form_values['form_id'];
  if ($form_values['form_id'] == 'user_admin_settings' && $form_values['xmlsitemap_user_default_priority'] != $form_values['xmlsitemap_user_old_default_priority']) {
    xmlsitemap_update_sitemap();
  }
  elseif ($form_id == 'user_admin_role') {
    $priority = db_result(db_query("SELECT priority FROM {xmlsitemap_user_role} WHERE rid = %d", $form_values['rid']));
    if ($form_values['op'] == t('Delete role')) {
      db_query("DELETE FROM {xmlsitemap_user_role} WHERE rid = %d", $form_values['rid']);
      if ($priority !== FALSE) {
        xmlsitemap_update_sitemap();
      }
    }
    elseif ($form_values['op'] == t('Save role')) {
      $row = new stdClass();
      $row->rid = $form_values['rid'];
      $row->priority = $form_values['xmlsitemap_user_role_priority'];
      drupal_write_record('xmlsitemap_user_role', $row, $priority !== FALSE ? 'rid' : NULL);
      xmlsitemap_update_sitemap();
    }
  }
}

/*****************************************************************************
 * Public functions.
 ****************************************************************************/

/**
 * Batch function used to update the module tables.
 * @param $op
 *  The type of update operation. It can be 'update' to update the existing
 *  data, or 'add' to add the data present in the core table but not in the
 * module table.
 * @param $context
 *  The context parameter passed from batch_process().
 */
function xmlsitemap_user_update_database(&$context) {
  if (!isset($context['sandbox']['progress'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['current_user'] = 0;
    $context['sandbox']['max'] = (integer) db_result(db_query('SELECT COUNT(u.uid)
      FROM {users} u
      LEFT JOIN {xmlsitemap_user} xu ON xu.uid = u.uid
      WHERE u.uid <> 0 
        AND xu.uid IS NULL')
    );
  }
  if ($context['sandbox']['max']) {
    $result = db_query_range('SELECT u.uid, u.created AS changed
      FROM {users} u
      LEFT JOIN {xmlsitemap_user} xu ON xu.uid = u.uid
      WHERE xu.uid IS NULL
        AND u.uid > %d
      ORDER BY u.uid ASC',
      $context['sandbox']['current_user'], 0, 1
    );
    if ($row = db_fetch_object($result)) {
      drupal_write_record('xmlsitemap_user', $row);
      $context['sandbox']['progress']++;
      $context['sandbox']['current_user'] = $row->uid;
      $context['results']['add'] = $context['sandbox']['progress'];
    }
    if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
      $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
    }
  }
}

/**
 * @} End of "addtogroup xmlsitemap".
 */
